# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

defmodule PutridParrot.Units.DataStorage do
    use ExUnit.Case

    test "Convert known Bits to Kilobits" do
        assert_in_delta PutridParrot.Units.Bits.to_kilobits(100.0), 0.1, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_kilobits(6021.0), 6.021, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_kilobits(9100.0), 9.1, 0.01;
    end

    test "Convert known Bits to Megabits" do
        assert_in_delta PutridParrot.Units.Bits.to_megabits(9000000.0), 9.0, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_megabits(123456.0), 0.123456, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_megabits(1900000.0), 1.9, 0.01;
    end

    test "Convert known Bits to Gigabits" do
        assert_in_delta PutridParrot.Units.Bits.to_gigabits(190000000.0), 0.19, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_gigabits(8009.0), 8.009e-6, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_gigabits(987654321.0), 0.987654321, 0.01;
    end

    test "Convert known Bits to Terabits" do
        assert_in_delta PutridParrot.Units.Bits.to_terabits(987654321234.0), 0.987654321234, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_terabits(1234567890123456.0), 1234.567890123455982, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_terabits(999888777666555.0), 999.888777666555029, 0.01;
    end

    test "Convert known Bits to Kilobytes" do
        assert_in_delta PutridParrot.Units.Bits.to_kilobytes(900.0), 0.1125, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_kilobytes(12345.0), 1.543125, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_kilobytes(6000.9), 0.7501125, 0.01;
    end

    test "Convert known Bits to Megabytes" do
        assert_in_delta PutridParrot.Units.Bits.to_megabytes(123456.0), 0.015432, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_megabytes(900800.0), 0.1126, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_megabytes(999888777.0), 124.986097125, 0.01;
    end

    test "Convert known Bits to Gigabytes" do
        assert_in_delta PutridParrot.Units.Bits.to_gigabytes(999888777.0), 0.124986097125, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_gigabytes(1.9e+9), 0.2375, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_gigabytes(80090077.0), 0.010011259625, 0.01;
    end

    test "Convert known Bits to Terabytes" do
        assert_in_delta PutridParrot.Units.Bits.to_terabytes(999888777666.0), 0.12498609720825, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_terabytes(12345678912345.0), 1.5432098640431251, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_terabytes(111999222888333.0), 13.9999028610416243, 0.01;
    end

    test "Convert known Bits to Kibibits" do
        assert_in_delta PutridParrot.Units.Bits.to_kibibits(1800.0), 1.757813, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_kibibits(888.0), 0.867188, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_kibibits(7687.0), 7.506836, 0.01;
    end

    test "Convert known Bits to Mebibits" do
        assert_in_delta PutridParrot.Units.Bits.to_mebibits(999888.0), 0.953567505, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_mebibits(1234567.0), 1.17737484, 0.01;
        assert_in_delta PutridParrot.Units.Bits.to_mebibits(900800.0), 0.859069824, 0.01;
    end

    test "Convert known Gigabits to Bits" do
        assert_in_delta PutridParrot.Units.Gigabits.to_bits(0.0009), 900000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_bits(0.00007), 70000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_bits(1.2e-5), 12000.0, 0.01;
    end

    test "Convert known Gigabits to Kilobits" do
        assert_in_delta PutridParrot.Units.Gigabits.to_kilobits(0.01), 10000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_kilobits(0.91), 910000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_kilobits(6.1), 6.1e+6, 0.01;
    end

    test "Convert known Gigabits to Megabits" do
        assert_in_delta PutridParrot.Units.Gigabits.to_megabits(6.1), 6100.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_megabits(0.961), 961.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_megabits(1.2e-3), 1.2, 0.01;
    end

    test "Convert known Gigabits to Terabits" do
        assert_in_delta PutridParrot.Units.Gigabits.to_terabits(1200.0), 1.2, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_terabits(90012.0), 90.012, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_terabits(8000.0), 8.0, 0.01;
    end

    test "Convert known Gigabits to Kilobytes" do
        assert_in_delta PutridParrot.Units.Gigabits.to_kilobytes(1.2), 150000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_kilobytes(0.9), 112500.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_kilobytes(0.001), 125.0, 0.01;
    end

    test "Convert known Gigabits to Megabytes" do
        assert_in_delta PutridParrot.Units.Gigabits.to_megabytes(0.9), 112.5, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_megabytes(1.2), 150.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_megabytes(80.1), 10012.5, 0.01;
    end

    test "Convert known Gigabits to Gigabytes" do
        assert_in_delta PutridParrot.Units.Gigabits.to_gigabytes(99.0), 12.375, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_gigabytes(123.123), 15.390375, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_gigabytes(8000.9), 1000.1125, 0.01;
    end

    test "Convert known Gigabits to Terabytes" do
        assert_in_delta PutridParrot.Units.Gigabits.to_terabytes(9000.0), 1.125, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_terabytes(1234567.0), 154.320875, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_terabytes(613.0), 0.076625, 0.01;
    end

    test "Convert known Gigabits to Kibibits" do
        assert_in_delta PutridParrot.Units.Gigabits.to_kibibits(0.8), 781250.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_kibibits(0.012), 11718.75, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_kibibits(0.002), 1953.125, 0.01;
    end

    test "Convert known Gigabits to Mebibits" do
        assert_in_delta PutridParrot.Units.Gigabits.to_mebibits(0.002), 1.9073486, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_mebibits(0.9), 858.30688476562, 0.01;
        assert_in_delta PutridParrot.Units.Gigabits.to_mebibits(6.1), 5817.413330078125, 0.01;
    end

    test "Convert known Gigabytes to Bits" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_bits(0.004), 32000000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_bits(0.012), 96000000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_bits(3.0e-9), 24.0, 0.01;
    end

    test "Convert known Gigabytes to Kilobits" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_kilobits(0.009), 72000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_kilobits(1.2e-4), 960.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_kilobits(0.0078), 62400.0, 0.01;
    end

    test "Convert known Gigabytes to Megabits" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_megabits(0.0078), 62.4, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_megabits(0.01), 80.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_megabits(0.001234), 9.872, 0.01;
    end

    test "Convert known Gigabytes to Gigabits" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_gigabits(5.0), 40.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_gigabits(1.2), 9.6, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_gigabits(0.01), 0.08, 0.01;
    end

    test "Convert known Gigabytes to Terabits" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_terabits(70.0), 0.56, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_terabits(9001.0), 72.008, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_terabits(768123.9), 6144.9912, 0.01;
    end

    test "Convert known Gigabytes to Kilobytes" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_kilobytes(0.2), 200000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_kilobytes(0.009), 9000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_kilobytes(0.00123), 1230.0, 0.01;
    end

    test "Convert known Gigabytes to Megabytes" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_megabytes(0.9), 900.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_megabytes(12.0), 12000.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_megabytes(35.6), 35600.0, 0.01;
    end

    test "Convert known Gigabytes to Terabytes" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_terabytes(35.6), 0.0356, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_terabytes(100.23), 0.10023, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_terabytes(900100.0), 900.1, 0.01;
    end

    test "Convert known Gigabytes to Kibibits" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_kibibits(0.05), 390625.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_kibibits(0.008), 62500.0, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_kibibits(0.00123), 9609.375, 0.01;
    end

    test "Convert known Gigabytes to Mebibits" do
        assert_in_delta PutridParrot.Units.Gigabytes.to_mebibits(0.009), 68.66451, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_mebibits(1.2), 9155.268, 0.01;
        assert_in_delta PutridParrot.Units.Gigabytes.to_mebibits(19.2), 146484.288, 0.01;
    end

    test "Convert known Kibibits to Bits" do
        assert_in_delta PutridParrot.Units.Kibibits.to_bits(2.0), 2048.0, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_bits(9.0), 9216.0, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_bits(17.8), 18227.2, 0.01;
    end

    test "Convert known Kibibits to Kilobits" do
        assert_in_delta PutridParrot.Units.Kibibits.to_kilobits(6.2), 6.3488, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_kilobits(0.9), 0.9216, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_kilobits(87.0), 89.088, 0.01;
    end

    test "Convert known Kibibits to Megabits" do
        assert_in_delta PutridParrot.Units.Kibibits.to_megabits(87.0), 0.089088, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_megabits(12.34), 0.01263616, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_megabits(123456.0), 126.418879, 0.01;
    end

    test "Convert known Kibibits to Gigabits" do
        assert_in_delta PutridParrot.Units.Kibibits.to_gigabits(123456.0), 0.126418944, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_gigabits(8000000.0), 8.192, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_gigabits(1276876.0), 1.307521024, 0.01;
    end

    test "Convert known Kibibits to Terabits" do
        assert_in_delta PutridParrot.Units.Kibibits.to_terabits(800000000.0), 0.8192, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_terabits(1.5e12), 1536.0, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_terabits(9999999.0), 0.01023999898, 0.01;
    end

    test "Convert known Kibibits to Kilobytes" do
        assert_in_delta PutridParrot.Units.Kibibits.to_kilobytes(919.0), 117.632, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_kilobytes(77.4), 9.9072, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_kilobytes(109.109), 13.965952, 0.01;
    end

    test "Convert known Kibibits to Megabytes" do
        assert_in_delta PutridParrot.Units.Kibibits.to_megabytes(1000.0), 0.128, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_megabytes(800.123), 0.102415744, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_megabytes(123456.0), 15.802368, 0.01;
    end

    test "Convert known Kibibits to Gigabytes" do
        assert_in_delta PutridParrot.Units.Kibibits.to_gigabytes(12345678.0), 1.580347926, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_gigabytes(8.0e12), 1024000.00, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_gigabytes(1.2e5), 0.01536, 0.01;
    end

    test "Convert known Kibibits to Terabytes" do
        assert_in_delta PutridParrot.Units.Kibibits.to_terabytes(120000000.0), 0.01536, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_terabytes(88.0e12), 11264.0, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_terabytes(9000000.0), 0.001152, 0.01;
    end

    test "Convert known Kibibits to Mebibits" do
        assert_in_delta PutridParrot.Units.Kibibits.to_mebibits(600.0), 0.5859375, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_mebibits(12345.0), 12.055664, 0.01;
        assert_in_delta PutridParrot.Units.Kibibits.to_mebibits(101.0), 0.0986328, 0.01;
    end

    test "Convert known Kilobits to Bits" do
        assert_in_delta PutridParrot.Units.Kilobits.to_bits(9.0), 9000.0, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_bits(6.7), 6700.0, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_bits(1.2345), 1234.5, 0.01;
    end

    test "Convert known Kilobits to Megabits" do
        assert_in_delta PutridParrot.Units.Kilobits.to_megabits(900.0), 0.9, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_megabits(12345.0), 12.345, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_megabits(9988.0), 9.988, 0.01;
    end

    test "Convert known Kilobits to Gigabits" do
        assert_in_delta PutridParrot.Units.Kilobits.to_gigabits(123456.0), 0.123456, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_gigabits(8000700.0), 8.0007, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_gigabits(191987578.0), 191.987578, 0.01;
    end

    test "Convert known Kilobits to Terabits" do
        assert_in_delta PutridParrot.Units.Kilobits.to_terabits(191987578.0), 0.191987578, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_terabits(9010081903.0), 9.010081903, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_terabits(123456789.0), 0.123456789, 0.01;
    end

    test "Convert known Kilobits to Kilobytes" do
        assert_in_delta PutridParrot.Units.Kilobits.to_kilobytes(80.0), 10.0, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_kilobytes(15.67), 1.95875, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_kilobytes(8007.09), 1000.88625, 0.01;
    end

    test "Convert known Kilobits to Megabytes" do
        assert_in_delta PutridParrot.Units.Kilobits.to_megabytes(123456.0), 15.432, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_megabytes(998877.0), 124.859625, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_megabytes(10090.0), 1.26125, 0.01;
    end

    test "Convert known Kilobits to Gigabytes" do
        assert_in_delta PutridParrot.Units.Kilobits.to_gigabytes(1828972.0), 0.2286215, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_gigabytes(879860.8), 0.1099826, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_gigabytes(78178971.0), 9.772371375, 0.01;
    end

    test "Convert known Kilobits to Terabytes" do
        assert_in_delta PutridParrot.Units.Kilobits.to_terabytes(1234567891.0), 0.154320986375, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_terabytes(999999098.0), 0.12499988725, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_terabytes(84618364142.0), 10.57729551775, 0.01;
    end

    test "Convert known Kilobits to Kibibits" do
        assert_in_delta PutridParrot.Units.Kilobits.to_kibibits(89.1), 87.01172, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_kibibits(7.1), 6.93359, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_kibibits(438.0), 427.734, 0.01;
    end

    test "Convert known Kilobits to Mebibits" do
        assert_in_delta PutridParrot.Units.Kilobits.to_mebibits(77790.0), 74.186325, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_mebibits(123456.0), 117.736816, 0.01;
        assert_in_delta PutridParrot.Units.Kilobits.to_mebibits(23972.0), 22.861481, 0.01;
    end

    test "Convert known Kilobytes to Bits" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_bits(123.456), 987648.0, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_bits(900.0), 7.2e+6, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_bits(100200.0), 801600000.0, 0.01;
    end

    test "Convert known Kilobytes to Kilobits" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_kilobits(4.0), 32.0, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_kilobits(1.2), 9.6, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_kilobits(88.1), 704.8, 0.01;
    end

    test "Convert known Kilobytes to Megabits" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_megabits(88.1), 0.7048, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_megabits(7.1), 0.0568, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_megabits(12.8), 0.1024, 0.01;
    end

    test "Convert known Kilobytes to Gigabits" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_gigabits(10080.0), 0.08064, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_gigabits(4.5e+9), 36000.0, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_gigabits(271279.0), 2.170232, 0.01;
    end

    test "Convert known Kilobytes to Terabits" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_terabits(9009000.0), 0.072072, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_terabits(7.2e9), 57.6, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_terabits(100100100900.0), 800.8008072, 0.01;
    end

    test "Convert known Kilobytes to Megabytes" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_megabytes(1009.0), 1.009, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_megabytes(8899.0), 8.899, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_megabytes(619.0), 0.619, 0.01;
    end

    test "Convert known Kilobytes to Gigabytes" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_gigabytes(900800.0), 0.9008, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_gigabytes(1234567.0), 1.234567, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_gigabytes(7.9e9), 7900.0, 0.01;
    end

    test "Convert known Kilobytes to Terabytes" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_terabytes(0.9), 9.0e-10, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_terabytes(140000000.0), 0.14, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_terabytes(7.0), 7.0e-9, 0.01;
    end

    test "Convert known Kilobytes to Kibibits" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_kibibits(0.009), 0.0703125, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_kibibits(6.0e+3), 46875.0, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_kibibits(1.23), 9.609375, 0.01;
    end

    test "Convert known Kilobytes to Mebibits" do
        assert_in_delta PutridParrot.Units.Kilobytes.to_mebibits(70.0), 0.534058, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_mebibits(9.0), 0.0686646, 0.01;
        assert_in_delta PutridParrot.Units.Kilobytes.to_mebibits(10022.0), 76.461792, 0.01;
    end

    test "Convert known Mebibits to Bits" do
        assert_in_delta PutridParrot.Units.Mebibits.to_bits(0.9), 943718.4, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_bits(0.006), 6291.456, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_bits(2.0), 2097152.0, 0.01;
    end

    test "Convert known Mebibits to Kilobits" do
        assert_in_delta PutridParrot.Units.Mebibits.to_kilobits(0.8), 838.861, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_kilobits(2.0), 2097.15, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_kilobits(0.23), 241.1725, 0.01;
    end

    test "Convert known Mebibits to Megabits" do
        assert_in_delta PutridParrot.Units.Mebibits.to_megabits(0.9), 0.943718, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_megabits(12.3), 12.89748, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_megabits(8.1), 8.49347, 0.01;
    end

    test "Convert known Mebibits to Gigabits" do
        assert_in_delta PutridParrot.Units.Mebibits.to_gigabits(12345.0), 12.944671, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_gigabits(100.0), 0.104858, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_gigabits(999.9), 1.0484711, 0.01;
    end

    test "Convert known Mebibits to Terabits" do
        assert_in_delta PutridParrot.Units.Mebibits.to_terabits(100009.0), 0.104867037, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_terabits(9876543.0), 10.35630595, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_terabits(1000900.0), 1.049519718, 0.01;
    end

    test "Convert known Mebibits to Kilobytes" do
        assert_in_delta PutridParrot.Units.Mebibits.to_kilobytes(4.0), 524.288, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_kilobytes(1.45), 190.0544, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_kilobytes(88.11), 11548.754, 0.01;
    end

    test "Convert known Mebibits to Megabytes" do
        assert_in_delta PutridParrot.Units.Mebibits.to_megabytes(109.0), 14.2868, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_megabytes(55.67), 7.2967782, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_megabytes(45678.0), 5987.1068, 0.01;
    end

    test "Convert known Mebibits to Gigabytes" do
        assert_in_delta PutridParrot.Units.Mebibits.to_gigabytes(4000.0), 0.524288311, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_gigabytes(90100.0), 11.80959421, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_gigabytes(1009.0), 0.132251727, 0.01;
    end

    test "Convert known Mebibits to Terabytes" do
        assert_in_delta PutridParrot.Units.Mebibits.to_terabytes(1000009.0), 0.1310731796, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_terabytes(90808080.0), 11.902396662, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_terabytes(5.2e12), 681574.4, 0.01;
    end

    test "Convert known Mebibits to Kibibits" do
        assert_in_delta PutridParrot.Units.Mebibits.to_kibibits(5.0), 5120.0, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_kibibits(1234.56), 1264189.44, 0.01;
        assert_in_delta PutridParrot.Units.Mebibits.to_kibibits(505.0), 517120.0, 0.01;
    end

    test "Convert known Megabits to Bits" do
        assert_in_delta PutridParrot.Units.Megabits.to_bits(0.34), 340000.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_bits(9.12), 9120000.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_bits(0.987), 987000.0, 0.01;
    end

    test "Convert known Megabits to Kilobits" do
        assert_in_delta PutridParrot.Units.Megabits.to_kilobits(0.77), 770.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_kilobits(5.0), 5000.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_kilobits(0.987), 987.0, 0.01;
    end

    test "Convert known Megabits to Gigabits" do
        assert_in_delta PutridParrot.Units.Megabits.to_gigabits(900.0), 0.9, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_gigabits(12345.0), 12.345, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_gigabits(189.1), 0.1891, 0.01;
    end

    test "Convert known Megabits to Terabits" do
        assert_in_delta PutridParrot.Units.Megabits.to_terabits(100200300.0), 100.2003, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_terabits(99887777.0), 99.887777, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_terabits(80009.0), 0.080009, 0.01;
    end

    test "Convert known Megabits to Kilobytes" do
        assert_in_delta PutridParrot.Units.Megabits.to_kilobytes(9.0), 1125.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_kilobytes(1.23), 153.75, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_kilobytes(98.1), 12262.5, 0.01;
    end

    test "Convert known Megabits to Megabytes" do
        assert_in_delta PutridParrot.Units.Megabits.to_megabytes(98.1), 12.2625, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_megabytes(10.9), 1.3625, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_megabytes(888.123), 111.015375, 0.01;
    end

    test "Convert known Megabits to Gigabytes" do
        assert_in_delta PutridParrot.Units.Megabits.to_gigabytes(900.0), 0.1125, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_gigabytes(10123.0), 1.265375, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_gigabytes(9988.0), 1.2485, 0.01;
    end

    test "Convert known Megabits to Terabytes" do
        assert_in_delta PutridParrot.Units.Megabits.to_terabytes(998877.0), 0.124859625, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_terabytes(100200400.0), 12.5250375, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_terabytes(9008877.0), 1.126109625, 0.01;
    end

    test "Convert known Megabits to Kibibits" do
        assert_in_delta PutridParrot.Units.Megabits.to_kibibits(12.0), 11718.756, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_kibibits(0.9), 878.906, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_kibibits(1.23), 1201.172, 0.01;
    end

    test "Convert known Megabits to Mebibits" do
        assert_in_delta PutridParrot.Units.Megabits.to_mebibits(4.5), 4.29153, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_mebibits(0.8), 0.762939, 0.01;
        assert_in_delta PutridParrot.Units.Megabits.to_mebibits(900.0), 858.307, 0.01;
    end

    test "Convert known Megabytes to Bits" do
        assert_in_delta PutridParrot.Units.Megabytes.to_bits(0.04), 320000.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_bits(0.0091), 72800.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_bits(3.0e-5), 240.0, 0.01;
    end

    test "Convert known Megabytes to Kilobits" do
        assert_in_delta PutridParrot.Units.Megabytes.to_kilobits(6.0), 48000.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_kilobits(0.3), 2400.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_kilobits(0.009), 72.0, 0.01;
    end

    test "Convert known Megabytes to Megabits" do
        assert_in_delta PutridParrot.Units.Megabytes.to_megabits(3.0), 24.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_megabits(0.9), 7.2, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_megabits(13.0), 104.0, 0.01;
    end

    test "Convert known Megabytes to Gigabits" do
        assert_in_delta PutridParrot.Units.Megabytes.to_gigabits(13.0), 0.104, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_gigabits(900.0), 7.2, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_gigabits(18000.0), 144.0, 0.01;
    end

    test "Convert known Megabytes to Terabits" do
        assert_in_delta PutridParrot.Units.Megabytes.to_terabits(18000.0), 0.144, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_terabits(9718290.0), 77.74632, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_terabits(9.0e12), 72000000.0, 0.01;
    end

    test "Convert known Megabytes to Kilobytes" do
        assert_in_delta PutridParrot.Units.Megabytes.to_kilobytes(6.0), 6000.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_kilobytes(0.9), 900.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_kilobytes(123.4), 123400.0, 0.01;
    end

    test "Convert known Megabytes to Gigabytes" do
        assert_in_delta PutridParrot.Units.Megabytes.to_gigabytes(123.4), 0.1234, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_gigabytes(900.0), 0.9, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_gigabytes(8.0e6), 8000.0, 0.01;
    end

    test "Convert known Megabytes to Terabytes" do
        assert_in_delta PutridParrot.Units.Megabytes.to_terabytes(80000.0), 0.08, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_terabytes(12345678.0), 12.345678, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_terabytes(900800.0), 0.9008, 0.01;
    end

    test "Convert known Megabytes to Kibibits" do
        assert_in_delta PutridParrot.Units.Megabytes.to_kibibits(6.0), 46875.0, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_kibibits(0.9), 7031.25, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_kibibits(0.03), 234.375, 0.01;
    end

    test "Convert known Megabytes to Mebibits" do
        assert_in_delta PutridParrot.Units.Megabytes.to_mebibits(0.03), 0.2288818, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_mebibits(4.5), 34.3323, 0.01;
        assert_in_delta PutridParrot.Units.Megabytes.to_mebibits(80.1), 611.1145, 0.01;
    end

    test "Convert known Terabits to Bits" do
        assert_in_delta PutridParrot.Units.Terabits.to_bits(0.0007), 700000000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_bits(1.23e-6), 1230000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_bits(0.00098), 980000000.0, 0.01;
    end

    test "Convert known Terabits to Kilobits" do
        assert_in_delta PutridParrot.Units.Terabits.to_kilobits(0.001), 1000000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_kilobits(6.1e-6), 6100.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_kilobits(0.00009), 90000.0, 0.01;
    end

    test "Convert known Terabits to Megabits" do
        assert_in_delta PutridParrot.Units.Terabits.to_megabits(0.09), 90000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_megabits(3.5e-4), 350.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_megabits(0.0123), 12300.0, 0.01;
    end

    test "Convert known Terabits to Gigabits" do
        assert_in_delta PutridParrot.Units.Terabits.to_gigabits(0.9), 900.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_gigabits(1.45), 1450.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_gigabits(8.19), 8190.0, 0.01;
    end

    test "Convert known Terabits to Kilobytes" do
        assert_in_delta PutridParrot.Units.Terabits.to_kilobytes(0.0009), 112500.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_kilobytes(3.14e-6), 392.5, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_kilobytes(0.001), 125000.0, 0.01;
    end

    test "Convert known Terabits to Megabytes" do
        assert_in_delta PutridParrot.Units.Terabits.to_megabytes(0.4), 50000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_megabytes(3.9e-3), 487.5, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_megabytes(0.007), 875.0, 0.01;
    end

    test "Convert known Terabits to Gigabytes" do
        assert_in_delta PutridParrot.Units.Terabits.to_gigabytes(0.009), 1.125, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_gigabytes(0.00123), 0.15375, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_gigabytes(8.1e-3), 1.0125, 0.01;
    end

    test "Convert known Terabits to Terabytes" do
        assert_in_delta PutridParrot.Units.Terabits.to_terabytes(0.3), 0.0375, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_terabytes(14.0), 1.75, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_terabytes(0.8), 0.1, 0.01;
    end

    test "Convert known Terabits to Kibibits" do
        assert_in_delta PutridParrot.Units.Terabits.to_kibibits(0.0009), 878906.25, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_kibibits(6.1e-6), 5957.031, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_kibibits(12.0e-9), 11.71875, 0.01;
    end

    test "Convert known Terabits to Mebibits" do
        assert_in_delta PutridParrot.Units.Terabits.to_mebibits(0.9), 858306.59999, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_mebibits(4.6e-3), 4386.9, 0.01;
        assert_in_delta PutridParrot.Units.Terabits.to_mebibits(0.00123), 1173.0194092, 0.01;
    end

    test "Convert known Terabytes to Bits" do
        assert_in_delta PutridParrot.Units.Terabytes.to_bits(0.00008), 640000000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_bits(1.2e-12), 9.6, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_bits(9.0), 7.2e+13, 0.01;
    end

    test "Convert known Terabytes to Kilobits" do
        assert_in_delta PutridParrot.Units.Terabytes.to_kilobits(0.009), 72000000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_kilobits(1.4e-6), 11200.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_kilobits(6.1e-5), 488000.0, 0.01;
    end

    test "Convert known Terabytes to Megabits" do
        assert_in_delta PutridParrot.Units.Terabytes.to_megabits(0.005), 40000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_megabits(0.000123), 984.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_megabits(0.00006), 480.0, 0.01;
    end

    test "Convert known Terabytes to Gigabits" do
        assert_in_delta PutridParrot.Units.Terabytes.to_gigabits(0.008), 64.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_gigabits(3.0e-7), 0.0024, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_gigabits(0.00023), 1.84, 0.01;
    end

    test "Convert known Terabytes to Terabits" do
        assert_in_delta PutridParrot.Units.Terabytes.to_terabits(5.0), 40.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_terabits(1.23), 9.84, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_terabits(800.0), 6400.0, 0.01;
    end

    test "Convert known Terabytes to Kilobytes" do
        assert_in_delta PutridParrot.Units.Terabytes.to_kilobytes(0.0009), 900000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_kilobytes(3.14e-7), 314.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_kilobytes(0.00063), 630000.0, 0.01;
    end

    test "Convert known Terabytes to Megabytes" do
        assert_in_delta PutridParrot.Units.Terabytes.to_megabytes(0.009), 9000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_megabytes(0.234), 234000.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_megabytes(2.0), 2.0e+6, 0.01;
    end

    test "Convert known Terabytes to Gigabytes" do
        assert_in_delta PutridParrot.Units.Terabytes.to_gigabytes(2.7), 2700.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_gigabytes(0.9), 900.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_gigabytes(0.0123), 12.3, 0.01;
    end

    test "Convert known Terabytes to Kibibits" do
        assert_in_delta PutridParrot.Units.Terabytes.to_kibibits(0.0009), 7031250.0, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_kibibits(1.23e-5), 96093.75, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_kibibits(0.0001), 781250.0, 0.01;
    end

    test "Convert known Terabytes to Mebibits" do
        assert_in_delta PutridParrot.Units.Terabytes.to_mebibits(0.01), 76293.95, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_mebibits(0.008), 61035.156, 0.01;
        assert_in_delta PutridParrot.Units.Terabytes.to_mebibits(2.0), 15258789.0625, 0.01;
    end

end
