# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

defmodule PutridParrot.Units.Force do
    use ExUnit.Case

    test "Convert known Dynes to Newtons" do
        assert_in_delta PutridParrot.Units.Dynes.to_newtons(900.0), 0.009, 0.01;
        assert_in_delta PutridParrot.Units.Dynes.to_newtons(1234.0), 0.01234, 0.01;
        assert_in_delta PutridParrot.Units.Dynes.to_newtons(46.0), 0.00046, 0.01;
    end

    test "Convert known Dynes to Poundals" do
        assert_in_delta PutridParrot.Units.Dynes.to_poundals(10099.0), 0.73046207, 0.01;
        assert_in_delta PutridParrot.Units.Dynes.to_poundals(80000.0), 5.7864111, 0.01;
        assert_in_delta PutridParrot.Units.Dynes.to_poundals(12345.0), 0.89291556, 0.01;
    end

    test "Convert known Dynes to Kilogram-force" do
        assert_in_delta PutridParrot.Units.Dynes.to_kilogramforce(123456.0), 0.125890085, 0.01;
        assert_in_delta PutridParrot.Units.Dynes.to_kilogramforce(80000.0), 0.081577297, 0.01;
        assert_in_delta PutridParrot.Units.Dynes.to_kilogramforce(987654321.0), 1007.12712394, 0.01;
    end

    test "Convert known Kilogram-force to Newtons" do
        assert_in_delta PutridParrot.Units.Kilogramforce.to_newtons(16.0), 156.906, 0.01;
        assert_in_delta PutridParrot.Units.Kilogramforce.to_newtons(9.3), 91.2018, 0.01;
        assert_in_delta PutridParrot.Units.Kilogramforce.to_newtons(5.0), 49.0332, 0.01;
    end

    test "Convert known Kilogram-force to Dynes" do
        assert_in_delta PutridParrot.Units.Kilogramforce.to_dynes(0.1), 98066.5, 0.01;
        assert_in_delta PutridParrot.Units.Kilogramforce.to_dynes(0.009), 8825.985, 0.01;
        assert_in_delta PutridParrot.Units.Kilogramforce.to_dynes(2.0), 1961330.0, 0.01;
    end

    test "Convert known Kilogram-force to Poundals" do
        assert_in_delta PutridParrot.Units.Kilogramforce.to_poundals(2.0), 141.863, 0.01;
        assert_in_delta PutridParrot.Units.Kilogramforce.to_poundals(8.4), 595.826, 0.01;
        assert_in_delta PutridParrot.Units.Kilogramforce.to_poundals(0.9), 63.8385, 0.01;
    end

    test "Convert known Newtons to Dynes" do
        assert_in_delta PutridParrot.Units.Newtons.to_dynes(0.7), 70000.0, 0.01;
        assert_in_delta PutridParrot.Units.Newtons.to_dynes(0.08), 8000.0, 0.01;
        assert_in_delta PutridParrot.Units.Newtons.to_dynes(2.3), 230000.0, 0.01;
    end

    test "Convert known Newtons to Poundals" do
        assert_in_delta PutridParrot.Units.Newtons.to_poundals(190.0), 1374.27, 0.01;
        assert_in_delta PutridParrot.Units.Newtons.to_poundals(0.7), 5.06311, 0.01;
        assert_in_delta PutridParrot.Units.Newtons.to_poundals(89.0), 643.738, 0.01;
    end

    test "Convert known Newtons to Kilogram-force" do
        assert_in_delta PutridParrot.Units.Newtons.to_kilogramforce(8.7), 0.887153, 0.01;
        assert_in_delta PutridParrot.Units.Newtons.to_kilogramforce(109.0), 11.1149, 0.01;
        assert_in_delta PutridParrot.Units.Newtons.to_kilogramforce(6.9), 0.703604, 0.01;
    end

    test "Convert known Poundals to Newtons" do
        assert_in_delta PutridParrot.Units.Poundals.to_newtons(800.0), 110.604, 0.01;
        assert_in_delta PutridParrot.Units.Poundals.to_newtons(8.2), 1.13369, 0.01;
        assert_in_delta PutridParrot.Units.Poundals.to_newtons(190.0), 26.2684, 0.01;
    end

    test "Convert known Poundals to Dynes" do
        assert_in_delta PutridParrot.Units.Poundals.to_dynes(0.01), 138.255, 0.01;
        assert_in_delta PutridParrot.Units.Poundals.to_dynes(2.0), 27651.0, 0.01;
        assert_in_delta PutridParrot.Units.Poundals.to_dynes(0.9), 12442.94589384, 0.01;
    end

    test "Convert known Poundals to Kilogram-force" do
        assert_in_delta PutridParrot.Units.Poundals.to_kilogramforce(34.0), 0.479335, 0.01;
        assert_in_delta PutridParrot.Units.Poundals.to_kilogramforce(101.1), 1.4253161, 0.01;
        assert_in_delta PutridParrot.Units.Poundals.to_kilogramforce(9.5), 0.133932, 0.01;
    end

end
