# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

defmodule PutridParrot.Units.Speed do
  use ExUnit.Case

  test "Convert known Feet Per Second to Miles Per Hour" do
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_milesperhour(14.5), 9.886364, 0.01
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_milesperhour(100.0), 68.1818, 0.01
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_milesperhour(1.6), 1.09091, 0.01
  end

  test "Convert known Feet Per Second to Kilometres Per Hour" do
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_kilometresperhour(1.5), 1.64592, 0.01
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_kilometresperhour(67.9), 74.50531, 0.01
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_kilometresperhour(109.0), 119.604, 0.01
  end

  test "Convert known Feet Per Second to Metres Per Second" do
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_metrespersecond(10.8), 3.29184, 0.01
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_metrespersecond(66.0), 20.1168, 0.01
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_metrespersecond(2.3), 0.70104, 0.01
  end

  test "Convert known Feet Per Second to Knots" do
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_knots(2.3), 1.36271, 0.01
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_knots(666.0), 394.594, 0.01
    assert_in_delta PutridParrot.Units.FeetPerSecond.to_knots(17.1), 10.13147, 0.01
  end

  test "Convert known Kilometres Per Hour to Miles Per Hour" do
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_milesperhour(67.0), 41.6319, 0.01
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_milesperhour(12.0), 7.45645, 0.01
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_milesperhour(6.3), 3.91464, 0.01
  end

  test "Convert known Kilometres Per Hour to Feet Per Second" do
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_feetpersecond(5.0), 4.55672, 0.01
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_feetpersecond(1.5), 1.36702, 0.01
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_feetpersecond(89.8), 81.83873, 0.01
  end

  test "Convert known Kilometres Per Hour to Metres Per Second" do
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_metrespersecond(67.0), 18.6111, 0.01
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_metrespersecond(5.9), 1.63889, 0.01
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_metrespersecond(900.0), 250.0, 0.01
  end

  test "Convert known Kilometres Per Hour to Knots" do
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_knots(900.0), 485.961, 0.01
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_knots(3.9), 2.10583, 0.01
    assert_in_delta PutridParrot.Units.KilometresPerHour.to_knots(12.0), 6.47948, 0.01
  end

  test "Convert known Knots to Miles Per Hour" do
    assert_in_delta PutridParrot.Units.Knots.to_milesperhour(8.0), 9.20624, 0.01
    assert_in_delta PutridParrot.Units.Knots.to_milesperhour(1.2), 1.38094, 0.01
    assert_in_delta PutridParrot.Units.Knots.to_milesperhour(670.0), 771.022, 0.01
  end

  test "Convert known Knots to Kilometres Per Hour" do
    assert_in_delta PutridParrot.Units.Knots.to_kilometresperhour(678.0), 1255.66, 0.01
    assert_in_delta PutridParrot.Units.Knots.to_kilometresperhour(1.8), 3.3336, 0.01
    assert_in_delta PutridParrot.Units.Knots.to_kilometresperhour(56.0), 103.712, 0.01
  end

  test "Convert known Knots to Feet Per Second" do
    assert_in_delta PutridParrot.Units.Knots.to_feetpersecond(56.0), 94.5174, 0.01
    assert_in_delta PutridParrot.Units.Knots.to_feetpersecond(4.7), 7.93271, 0.01
    assert_in_delta PutridParrot.Units.Knots.to_feetpersecond(3.0), 5.06343, 0.01
  end

  test "Convert known Knots to Metres Per Second" do
    assert_in_delta PutridParrot.Units.Knots.to_metrespersecond(5.0), 2.57222, 0.01
    assert_in_delta PutridParrot.Units.Knots.to_metrespersecond(9.1), 4.68144, 0.01
    assert_in_delta PutridParrot.Units.Knots.to_metrespersecond(190.0), 97.7444, 0.01
  end

  test "Convert known Metres Per Second to Miles Per Hour" do
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_milesperhour(13.0), 29.0802, 0.01
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_milesperhour(6.7), 14.9875, 0.01
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_milesperhour(140.0), 313.171, 0.01
  end

  test "Convert known Metres Per Second to Kilometres Per Hour" do
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_kilometresperhour(800.0), 2880.0, 0.01
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_kilometresperhour(7.8), 28.08, 0.01
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_kilometresperhour(9000.0), 32400.0, 0.01
  end

  test "Convert known Metres Per Second to Feet Per Second" do
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_feetpersecond(9000.0), 29527.56, 0.01
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_feetpersecond(3.4), 11.1549, 0.01
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_feetpersecond(12.0), 39.3701, 0.01
  end

  test "Convert known Metres Per Second to Knots" do
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_knots(12.0), 23.3261, 0.01
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_knots(6.3), 12.2462, 0.01
    assert_in_delta PutridParrot.Units.MetresPerSecond.to_knots(9.0), 17.4946, 0.01
  end

  test "Convert known Miles Per Hour to Kilometres Per Hour" do
    assert_in_delta PutridParrot.Units.MilesPerHour.to_kilometresperhour(345.0), 555.224, 0.01
    assert_in_delta PutridParrot.Units.MilesPerHour.to_kilometresperhour(1.6), 2.57495, 0.01
    assert_in_delta PutridParrot.Units.MilesPerHour.to_kilometresperhour(0.5), 0.804672, 0.01
  end

  test "Convert known Miles Per Hour to Feet Per Second" do
    assert_in_delta PutridParrot.Units.MilesPerHour.to_feetpersecond(0.5), 0.733333, 0.01
    assert_in_delta PutridParrot.Units.MilesPerHour.to_feetpersecond(123.0), 180.4, 0.01
    assert_in_delta PutridParrot.Units.MilesPerHour.to_feetpersecond(4.5), 6.6, 0.01
  end

  test "Convert known Miles Per Hour to Metres Per Second" do
    assert_in_delta PutridParrot.Units.MilesPerHour.to_metrespersecond(4.5), 2.01168, 0.01
    assert_in_delta PutridParrot.Units.MilesPerHour.to_metrespersecond(100.0), 44.704, 0.01
    assert_in_delta PutridParrot.Units.MilesPerHour.to_metrespersecond(40.0), 17.8816, 0.01
  end

  test "Convert known Miles Per Hour to Knots" do
    assert_in_delta PutridParrot.Units.MilesPerHour.to_knots(30.0), 26.0693, 0.01
    assert_in_delta PutridParrot.Units.MilesPerHour.to_knots(4.5), 3.91039, 0.01
    assert_in_delta PutridParrot.Units.MilesPerHour.to_knots(55.0), 47.7937, 0.01
  end
end
