# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

defmodule PutridParrot.Units.Temperature do
  use ExUnit.Case

  test "Convert known Celsius to Fahrenheit" do
    assert_in_delta PutridParrot.Units.Celsius.to_fahrenheit(32.0), 89.6, 0.01
    assert_in_delta PutridParrot.Units.Celsius.to_fahrenheit(0.9), 33.62, 0.01
    assert_in_delta PutridParrot.Units.Celsius.to_fahrenheit(0.0), 32.0, 0.01
  end

  test "Convert known Celsius to Kelvin" do
    assert_in_delta PutridParrot.Units.Celsius.to_kelvin(1.0), 274.15, 0.01
    assert_in_delta PutridParrot.Units.Celsius.to_kelvin(9.9), 283.05, 0.01
    assert_in_delta PutridParrot.Units.Celsius.to_kelvin(100.0), 373.15, 0.01
  end

  test "Convert known Celsius to Rankine" do
    assert_in_delta PutridParrot.Units.Celsius.to_rankine(900.0), 2111.67, 0.01
    assert_in_delta PutridParrot.Units.Celsius.to_rankine(12.0), 513.27, 0.01
    assert_in_delta PutridParrot.Units.Celsius.to_rankine(-3.0), 486.27, 0.01
  end

  test "Convert known Celsius to Reaumur" do
    assert_in_delta PutridParrot.Units.Celsius.to_reaumur(123.0), 98.4, 0.01
    assert_in_delta PutridParrot.Units.Celsius.to_reaumur(15.67), 12.536, 0.01
    assert_in_delta PutridParrot.Units.Celsius.to_reaumur(87.0), 69.6, 0.01
  end

  test "Convert known Fahrenheit to Celsius" do
    assert_in_delta PutridParrot.Units.Fahrenheit.to_celsius(109.0), 42.7778, 0.01
    assert_in_delta PutridParrot.Units.Fahrenheit.to_celsius(56.9), 13.83333, 0.01
    assert_in_delta PutridParrot.Units.Fahrenheit.to_celsius(102.0), 38.8889, 0.01
  end

  test "Convert known Fahrenheit to Kelvin" do
    assert_in_delta PutridParrot.Units.Fahrenheit.to_kelvin(34.5), 274.5389, 0.01
    assert_in_delta PutridParrot.Units.Fahrenheit.to_kelvin(901.0), 755.928, 0.01
    assert_in_delta PutridParrot.Units.Fahrenheit.to_kelvin(23.9), 268.65, 0.01
  end

  test "Convert known Fahrenheit to Rankine" do
    assert_in_delta PutridParrot.Units.Fahrenheit.to_rankine(123.0), 582.67, 0.01
    assert_in_delta PutridParrot.Units.Fahrenheit.to_rankine(9.2), 468.87, 0.01
    assert_in_delta PutridParrot.Units.Fahrenheit.to_rankine(0.2), 459.87, 0.01
  end

  test "Convert known Fahrenheit to Reaumur" do
    assert_in_delta PutridParrot.Units.Fahrenheit.to_reaumur(67.0), 15.555555556, 0.01
    assert_in_delta PutridParrot.Units.Fahrenheit.to_reaumur(1.6), -13.511111111, 0.01
    assert_in_delta PutridParrot.Units.Fahrenheit.to_reaumur(900.0), 385.77777778, 0.01
  end

  test "Convert known Kelvin to Celsius" do
    assert_in_delta PutridParrot.Units.Kelvin.to_celsius(80.0), -193.15, 0.01
    assert_in_delta PutridParrot.Units.Kelvin.to_celsius(0.9), -272.25, 0.01
    assert_in_delta PutridParrot.Units.Kelvin.to_celsius(305.15), 32.0, 0.01
  end

  test "Convert known Kelvin to Fahrenheit" do
    assert_in_delta PutridParrot.Units.Kelvin.to_fahrenheit(123.4), -237.55, 0.01
    assert_in_delta PutridParrot.Units.Kelvin.to_fahrenheit(800.0), 980.33, 0.01
    assert_in_delta PutridParrot.Units.Kelvin.to_fahrenheit(99.999), -279.6718, 0.01
  end

  test "Convert known Kelvin to Rankine" do
    assert_in_delta PutridParrot.Units.Kelvin.to_rankine(156.0), 280.8, 0.01
    assert_in_delta PutridParrot.Units.Kelvin.to_rankine(8.2), 14.76, 0.01
    assert_in_delta PutridParrot.Units.Kelvin.to_rankine(0.8), 1.44, 0.01
  end

  test "Convert known Kelvin to Reaumur" do
    assert_in_delta PutridParrot.Units.Kelvin.to_reaumur(900.0), 501.48, 0.01
    assert_in_delta PutridParrot.Units.Kelvin.to_reaumur(1.3), -217.48, 0.01
    assert_in_delta PutridParrot.Units.Kelvin.to_reaumur(60.0), -170.52, 0.01
  end

  test "Convert known Rankine to Celsius" do
    assert_in_delta PutridParrot.Units.Rankine.to_celsius(190.0), -167.59444444, 0.01
    assert_in_delta PutridParrot.Units.Rankine.to_celsius(0.7), -272.76111111, 0.01
    assert_in_delta PutridParrot.Units.Rankine.to_celsius(900.0), 226.85, 0.01
  end

  test "Convert known Rankine to Fahrenheit" do
    assert_in_delta PutridParrot.Units.Rankine.to_fahrenheit(109.0), -350.67, 0.01
    assert_in_delta PutridParrot.Units.Rankine.to_fahrenheit(3567.0), 3107.33, 0.01
    assert_in_delta PutridParrot.Units.Rankine.to_fahrenheit(9.0), -450.67, 0.01
  end

  test "Convert known Rankine to Kelvin" do
    assert_in_delta PutridParrot.Units.Rankine.to_kelvin(123.0), 68.333333333, 0.01
    assert_in_delta PutridParrot.Units.Rankine.to_kelvin(0.9), 0.5, 0.01
    assert_in_delta PutridParrot.Units.Rankine.to_kelvin(23.0), 12.777777778, 0.01
  end

  test "Convert known Rankine to Reaumur" do
    assert_in_delta PutridParrot.Units.Rankine.to_reaumur(900.0), 181.48, 0.01
    assert_in_delta PutridParrot.Units.Rankine.to_reaumur(34.9), -203.00888889, 0.01
    assert_in_delta PutridParrot.Units.Rankine.to_reaumur(0.7), -218.20888889, 0.01
  end

  test "Convert known Reaumur to Kelvin" do
    assert_in_delta PutridParrot.Units.Reaumur.to_kelvin(128.0), 433.15, 0.01
    assert_in_delta PutridParrot.Units.Reaumur.to_kelvin(7.4), 282.4, 0.01
    assert_in_delta PutridParrot.Units.Reaumur.to_kelvin(1.5), 275.025, 0.01
  end

  test "Convert known Reaumur to Celsius" do
    assert_in_delta PutridParrot.Units.Reaumur.to_celsius(1.5), 1.875, 0.01
    assert_in_delta PutridParrot.Units.Reaumur.to_celsius(23.9), 29.875, 0.01
    assert_in_delta PutridParrot.Units.Reaumur.to_celsius(0.3), 0.375, 0.01
  end

  test "Convert known Reaumur to Fahrenheit" do
    assert_in_delta PutridParrot.Units.Reaumur.to_fahrenheit(0.3), 32.675, 0.01
    assert_in_delta PutridParrot.Units.Reaumur.to_fahrenheit(87.0), 227.75, 0.01
    assert_in_delta PutridParrot.Units.Reaumur.to_fahrenheit(34.1), 108.725, 0.01
  end

  test "Convert known Reaumur to Rankine" do
    assert_in_delta PutridParrot.Units.Reaumur.to_rankine(34.1), 568.395, 0.01
    assert_in_delta PutridParrot.Units.Reaumur.to_rankine(10.6), 515.52, 0.01
    assert_in_delta PutridParrot.Units.Reaumur.to_rankine(1.9), 495.945, 0.01
  end
end
