# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

defmodule PutridParrot.Units.Time do
  use ExUnit.Case

  test "Convert known Days to Milliseconds" do
    assert_in_delta PutridParrot.Units.Days.to_milliseconds(0.0009), 77760.0, 0.01
    assert_in_delta PutridParrot.Units.Days.to_milliseconds(0.03), 2_592_000.0, 0.01
    assert_in_delta PutridParrot.Units.Days.to_milliseconds(0.006), 518_400.0, 0.01
  end

  test "Convert known Days to Seconds" do
    assert_in_delta PutridParrot.Units.Days.to_seconds(1.4), 120_960.0, 0.01
    assert_in_delta PutridParrot.Units.Days.to_seconds(0.06), 5184.0, 0.01
    assert_in_delta PutridParrot.Units.Days.to_seconds(0.2), 17280.0, 0.01
  end

  test "Convert known Days to Minutes" do
    assert_in_delta PutridParrot.Units.Days.to_minutes(34.0), 48960.0, 0.01
    assert_in_delta PutridParrot.Units.Days.to_minutes(0.06), 86.4, 0.01
    assert_in_delta PutridParrot.Units.Days.to_minutes(8.1), 11664.0, 0.01
  end

  test "Convert known Days to Hours" do
    assert_in_delta PutridParrot.Units.Days.to_hours(8.1), 194.4, 0.01
    assert_in_delta PutridParrot.Units.Days.to_hours(0.2), 4.8, 0.01
    assert_in_delta PutridParrot.Units.Days.to_hours(121.0), 2904.0, 0.01
  end

  test "Convert known Days to Weeks" do
    assert_in_delta PutridParrot.Units.Days.to_weeks(121.0), 17.2857, 0.01
    assert_in_delta PutridParrot.Units.Days.to_weeks(7.2), 1.02857, 0.01
    assert_in_delta PutridParrot.Units.Days.to_weeks(0.9), 0.128571, 0.01
  end

  test "Convert known Days to Months" do
    assert_in_delta PutridParrot.Units.Days.to_months(0.9), 0.029589, 0.01
    assert_in_delta PutridParrot.Units.Days.to_months(108.0), 3.55068, 0.01
    assert_in_delta PutridParrot.Units.Days.to_months(55.0), 1.80822, 0.01
  end

  test "Convert known Days to Years" do
    assert_in_delta PutridParrot.Units.Days.to_years(55.0), 0.150685, 0.01
    assert_in_delta PutridParrot.Units.Days.to_years(123.0), 0.336986, 0.01
    assert_in_delta PutridParrot.Units.Days.to_years(900.0), 2.46575, 0.01
  end

  test "Convert known Hours to Milliseconds" do
    assert_in_delta PutridParrot.Units.Hours.to_milliseconds(0.006), 21600.0, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_milliseconds(0.09), 324_000.0, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_milliseconds(0.007), 25200.0, 0.01
  end

  test "Convert known Hours to Seconds" do
    assert_in_delta PutridParrot.Units.Hours.to_seconds(12.0), 43200.0, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_seconds(3.2), 11520.0, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_seconds(0.3), 1080.0, 0.01
  end

  test "Convert known Hours to Minutes" do
    assert_in_delta PutridParrot.Units.Hours.to_minutes(0.3), 18.0, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_minutes(700.0), 42000.0, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_minutes(4.8), 288.0, 0.01
  end

  test "Convert known Hours to Days" do
    assert_in_delta PutridParrot.Units.Hours.to_days(4.8), 0.2, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_days(190.0), 7.91667, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_days(8.5), 0.354167, 0.01
  end

  test "Convert known Hours to Weeks" do
    assert_in_delta PutridParrot.Units.Hours.to_weeks(800.0), 4.7619, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_weeks(90.0), 0.535714, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_weeks(102.0), 0.607143, 0.01
  end

  test "Convert known Hours to Months" do
    assert_in_delta PutridParrot.Units.Hours.to_months(102.0), 0.139726, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_months(9876.0), 13.52875, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_months(100.8), 0.13808204, 0.01
  end

  test "Convert known Hours to Years" do
    assert_in_delta PutridParrot.Units.Hours.to_years(9000.0), 1.027397, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_years(1003.0), 0.1144977, 0.01
    assert_in_delta PutridParrot.Units.Hours.to_years(809.0), 0.0923516, 0.01
  end

  test "Convert known Milliseconds to Seconds" do
    assert_in_delta PutridParrot.Units.Milliseconds.to_seconds(8.0), 0.008, 0.01
    assert_in_delta PutridParrot.Units.Milliseconds.to_seconds(780.0), 0.78, 0.01
    assert_in_delta PutridParrot.Units.Milliseconds.to_seconds(900.0), 0.9, 0.01
  end

  test "Convert known Milliseconds to Minutes" do
    assert_in_delta PutridParrot.Units.Milliseconds.to_minutes(900.0), 0.015, 0.01
    assert_in_delta PutridParrot.Units.Milliseconds.to_minutes(67000.0), 1.1166667, 0.01
    assert_in_delta PutridParrot.Units.Milliseconds.to_minutes(1_234_567.0), 20.57611667, 0.01
  end

  test "Convert known Milliseconds to Hours" do
    assert_in_delta PutridParrot.Units.Milliseconds.to_hours(1_234_567.0), 0.3429352778, 0.01
    assert_in_delta PutridParrot.Units.Milliseconds.to_hours(100_900.0), 0.0280277778, 0.01
    assert_in_delta PutridParrot.Units.Milliseconds.to_hours(46000.0), 0.012777778, 0.01
  end

  test "Convert known Milliseconds to Days" do
    assert_in_delta PutridParrot.Units.Milliseconds.to_days(9_000_000.0), 0.1041666667, 0.01
    assert_in_delta PutridParrot.Units.Milliseconds.to_days(123_456_789.0), 1.42889802083, 0.01
    assert_in_delta PutridParrot.Units.Milliseconds.to_days(89_008_900.0), 1.0301956019, 0.01
  end

  test "Convert known Milliseconds to Weeks" do
    assert_in_delta PutridParrot.Units.Milliseconds.to_weeks(89_008_900.0), 0.14717080026, 0.01

    assert_in_delta PutridParrot.Units.Milliseconds.to_weeks(1_234_567_890.0),
                    2.041282886905,
                    0.01

    assert_in_delta PutridParrot.Units.Milliseconds.to_weeks(100_200_300.0), 0.165675099206, 0.01
  end

  test "Convert known Milliseconds to Months" do
    assert_in_delta PutridParrot.Units.Milliseconds.to_months(100_200_300_400.0),
                    38.102653412154631,
                    0.01

    assert_in_delta PutridParrot.Units.Milliseconds.to_months(90_001_000.0), 0.034246918329, 0.01

    assert_in_delta PutridParrot.Units.Milliseconds.to_months(8_888_888_888.0),
                    3.382374104552,
                    0.01
  end

  test "Convert known Milliseconds to Years" do
    assert_in_delta PutridParrot.Units.Milliseconds.to_years(8_888_888_888.0),
                    0.28167767558793383,
                    0.01

    assert_in_delta PutridParrot.Units.Milliseconds.to_years(123_456_789_123.0),
                    3.9121899074093087,
                    0.01

    assert_in_delta PutridParrot.Units.Milliseconds.to_years(900_080_007_000.0),
                    28.522399977032002,
                    0.01
  end

  test "Convert known Minutes to Milliseconds" do
    assert_in_delta PutridParrot.Units.Minutes.to_milliseconds(0.007), 420.0, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_milliseconds(0.8), 48000.0, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_milliseconds(9.0), 540_000.0, 0.01
  end

  test "Convert known Minutes to Seconds" do
    assert_in_delta PutridParrot.Units.Minutes.to_seconds(90.0), 5400.0, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_seconds(0.9), 54.0, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_seconds(123.0), 7380.0, 0.01
  end

  test "Convert known Minutes to Hours" do
    assert_in_delta PutridParrot.Units.Minutes.to_hours(123.0), 2.05, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_hours(77.0), 1.28333, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_hours(0.8), 0.0133333, 0.01
  end

  test "Convert known Minutes to Days" do
    assert_in_delta PutridParrot.Units.Minutes.to_days(800.0), 0.555556, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_days(190.0), 0.131944, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_days(55.0), 0.0381944, 0.01
  end

  test "Convert known Minutes to Weeks" do
    assert_in_delta PutridParrot.Units.Minutes.to_weeks(1900.0), 0.1884921, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_weeks(800.0), 0.0793651, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_weeks(12345.0), 1.2247024, 0.01
  end

  test "Convert known Minutes to Months" do
    assert_in_delta PutridParrot.Units.Minutes.to_months(1234.0), 0.02817349, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_months(90000.0), 2.0547923, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_months(7100.0), 0.1621003, 0.01
  end

  test "Convert known Minutes to Years" do
    assert_in_delta PutridParrot.Units.Minutes.to_years(900_800.0), 1.71385084, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_years(12345.0), 0.023487443, 0.01
    assert_in_delta PutridParrot.Units.Minutes.to_years(610_910.0), 1.16230974, 0.01
  end

  test "Convert known Months to Milliseconds" do
    assert_in_delta PutridParrot.Units.Months.to_milliseconds(0.00034), 894_113.64, 0.01
    assert_in_delta PutridParrot.Units.Months.to_milliseconds(0.001), 2_629_746.0, 0.01
    assert_in_delta PutridParrot.Units.Months.to_milliseconds(0.006), 15_778_476.0, 0.01
  end

  test "Convert known Months to Seconds" do
    assert_in_delta PutridParrot.Units.Months.to_seconds(0.03), 78840.00, 0.01
    assert_in_delta PutridParrot.Units.Months.to_seconds(0.1), 262_800.0, 0.01
    assert_in_delta PutridParrot.Units.Months.to_seconds(0.008), 21024.0, 0.01
  end

  test "Convert known Months to Minutes" do
    assert_in_delta PutridParrot.Units.Months.to_minutes(0.7), 30660.0, 0.01
    assert_in_delta PutridParrot.Units.Months.to_minutes(1.4), 61319.99, 0.01
    assert_in_delta PutridParrot.Units.Months.to_minutes(5.0), 219_000.0, 0.01
  end

  test "Convert known Months to Hours" do
    assert_in_delta PutridParrot.Units.Months.to_hours(4.0), 2920.0, 0.01
    assert_in_delta PutridParrot.Units.Months.to_hours(0.3), 219.0, 0.01
    assert_in_delta PutridParrot.Units.Months.to_hours(4.5), 3285.0, 0.01
  end

  test "Convert known Months to Days" do
    assert_in_delta PutridParrot.Units.Months.to_days(4.5), 136.875, 0.01
    assert_in_delta PutridParrot.Units.Months.to_days(90.0), 2737.5029, 0.01
    assert_in_delta PutridParrot.Units.Months.to_days(0.4), 12.1667, 0.01
  end

  test "Convert known Months to Weeks" do
    assert_in_delta PutridParrot.Units.Months.to_weeks(0.5), 2.17262, 0.01
    assert_in_delta PutridParrot.Units.Months.to_weeks(88.0), 382.381120, 0.01
    assert_in_delta PutridParrot.Units.Months.to_weeks(12.6), 54.75006, 0.01
  end

  test "Convert known Months to Years" do
    assert_in_delta PutridParrot.Units.Months.to_years(12.6), 1.050001, 0.01
    assert_in_delta PutridParrot.Units.Months.to_years(109.0), 9.08334, 0.01
    assert_in_delta PutridParrot.Units.Months.to_years(23.0), 1.91667, 0.01
  end

  test "Convert known Nanoseconds to Microseconds" do
    assert_in_delta PutridParrot.Units.Nanoseconds.to_microseconds(1234.0), 1.234, 0.01
    assert_in_delta PutridParrot.Units.Nanoseconds.to_microseconds(90.9), 0.0909, 0.01
    assert_in_delta PutridParrot.Units.Nanoseconds.to_microseconds(70000.0), 70.0, 0.01
  end

  test "Convert known Nanoseconds to Milliseconds" do
    assert_in_delta PutridParrot.Units.Nanoseconds.to_milliseconds(70000.0), 0.07, 0.01
    assert_in_delta PutridParrot.Units.Nanoseconds.to_milliseconds(123_456.0), 0.123456, 0.01
    assert_in_delta PutridParrot.Units.Nanoseconds.to_milliseconds(900_900.0), 0.9009, 0.01
  end

  test "Convert known Nanoseconds to Seconds" do
    assert_in_delta PutridParrot.Units.Nanoseconds.to_seconds(900_000_000.0), 0.9, 0.01
    assert_in_delta PutridParrot.Units.Nanoseconds.to_seconds(123_456_789.0), 0.123456789, 0.01
    assert_in_delta PutridParrot.Units.Nanoseconds.to_seconds(800_400_700.0), 0.8004007, 0.01
  end

  test "Convert known Nanoseconds to Minutes" do
    assert_in_delta PutridParrot.Units.Nanoseconds.to_minutes(1_234_567_890.0), 0.0205761315, 0.01

    assert_in_delta PutridParrot.Units.Nanoseconds.to_minutes(800_400_700.0),
                    0.0133400116667,
                    0.01

    assert_in_delta PutridParrot.Units.Nanoseconds.to_minutes(800_100_800.0),
                    0.0133350133333,
                    0.01
  end

  test "Convert known Nanoseconds to Hours" do
    assert_in_delta PutridParrot.Units.Nanoseconds.to_hours(1_234_567_890_123.0),
                    0.3429355250341667,
                    0.01

    assert_in_delta PutridParrot.Units.Nanoseconds.to_hours(900_800_700_600.0),
                    0.250222416833333,
                    0.01

    assert_in_delta PutridParrot.Units.Nanoseconds.to_hours(66_677_788_999.0),
                    0.018521608055278,
                    0.01
  end

  test "Convert known Seconds to Milliseconds" do
    assert_in_delta PutridParrot.Units.Seconds.to_milliseconds(9.0), 9000.0, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_milliseconds(3.1), 3100.0, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_milliseconds(0.9), 900.0, 0.01
  end

  test "Convert known Seconds to Minutes" do
    assert_in_delta PutridParrot.Units.Seconds.to_minutes(100.0), 1.66667, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_minutes(9000.0), 150.0, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_minutes(2300.0), 38.33333, 0.01
  end

  test "Convert known Seconds to Hours" do
    assert_in_delta PutridParrot.Units.Seconds.to_hours(2300.0), 0.6388889, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_hours(9999.0), 2.7775, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_hours(36000.0), 10.0, 0.01
  end

  test "Convert known Seconds to Days" do
    assert_in_delta PutridParrot.Units.Seconds.to_days(36000.0), 0.41666667, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_days(90000.0), 1.0416667, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_days(190_000.0), 2.19907407, 0.01
  end

  test "Convert known Seconds to Weeks" do
    assert_in_delta PutridParrot.Units.Seconds.to_weeks(190_000.0), 0.314153439, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_weeks(1_234_567.0), 2.041281415, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_weeks(100_200.0), 0.165674603, 0.01
  end

  test "Convert known Seconds to Months" do
    assert_in_delta PutridParrot.Units.Seconds.to_months(1_000_000.0), 0.380517087, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_months(9_876_543.0), 3.75819337, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_months(200_900.0), 0.0764458827, 0.01
  end

  test "Convert known Seconds to Years" do
    assert_in_delta PutridParrot.Units.Seconds.to_years(123_456_789.0), 3.91478909817, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_years(100_900.0), 0.00319951801, 0.01
    assert_in_delta PutridParrot.Units.Seconds.to_years(987_654.0), 0.0313183029, 0.01
  end

  test "Convert known Weeks to Milliseconds" do
    assert_in_delta PutridParrot.Units.Weeks.to_milliseconds(0.001), 604_800.0, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_milliseconds(0.005), 3_024_000.0, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_milliseconds(0.0009), 544_320.0, 0.01
  end

  test "Convert known Weeks to Seconds" do
    assert_in_delta PutridParrot.Units.Weeks.to_seconds(0.1), 60480.0, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_seconds(0.08), 48384.0, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_seconds(3.0), 1_814_400.0, 0.01
  end

  test "Convert known Weeks to Minutes" do
    assert_in_delta PutridParrot.Units.Weeks.to_minutes(2.0), 20160.0, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_minutes(0.4), 4032.0, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_minutes(0.02), 201.6, 0.01
  end

  test "Convert known Weeks to Hours" do
    assert_in_delta PutridParrot.Units.Weeks.to_hours(0.02), 3.36, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_hours(77.0), 12936.0, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_hours(9.2), 1545.6, 0.01
  end

  test "Convert known Weeks to Days" do
    assert_in_delta PutridParrot.Units.Weeks.to_days(9.2), 64.4, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_days(169.0), 1183.0, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_days(4.0), 28.0, 0.01
  end

  test "Convert known Weeks to Months" do
    assert_in_delta PutridParrot.Units.Weeks.to_months(4.0), 0.920547, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_months(900.0), 207.12319687, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_months(3.8), 0.87452, 0.01
  end

  test "Convert known Weeks to Years" do
    assert_in_delta PutridParrot.Units.Weeks.to_years(3.0), 0.0575342, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_years(235.0), 4.50685, 0.01
    assert_in_delta PutridParrot.Units.Weeks.to_years(1090.0), 20.90411, 0.01
  end

  test "Convert known Years to Milliseconds" do
    assert_in_delta PutridParrot.Units.Years.to_milliseconds(0.001), 31_556_952.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_milliseconds(0.0009), 28_401_256.8, 0.01
    assert_in_delta PutridParrot.Units.Years.to_milliseconds(0.00034), 10_729_363.680000002, 0.01
  end

  test "Convert known Years to Seconds" do
    assert_in_delta PutridParrot.Units.Years.to_seconds(0.06), 1_892_160.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_seconds(0.009), 283_824.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_seconds(0.02), 630_720.0, 0.01
  end

  test "Convert known Years to Minutes" do
    assert_in_delta PutridParrot.Units.Years.to_minutes(0.02), 10512.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_minutes(0.3), 157_680.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_minutes(0.001), 525.6, 0.01
  end

  test "Convert known Years to Hours" do
    assert_in_delta PutridParrot.Units.Years.to_hours(0.001), 8.76, 0.01
    assert_in_delta PutridParrot.Units.Years.to_hours(0.3), 2628.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_hours(2.0), 17520.0, 0.01
  end

  test "Convert known Years to Days" do
    assert_in_delta PutridParrot.Units.Years.to_days(2.0), 730.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_days(1009.0), 368_285.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_days(7.0), 2555.0, 0.01
  end

  test "Convert known Years to Weeks" do
    assert_in_delta PutridParrot.Units.Years.to_weeks(7.0), 365.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_weeks(1.3), 67.7857, 0.01
    assert_in_delta PutridParrot.Units.Years.to_weeks(88.0), 4588.5839, 0.01
  end

  test "Convert known Years to Months" do
    assert_in_delta PutridParrot.Units.Years.to_months(6.0), 71.9999, 0.01
    assert_in_delta PutridParrot.Units.Years.to_months(12.0), 144.0, 0.01
    assert_in_delta PutridParrot.Units.Years.to_months(0.3), 3.6, 0.01
  end
end
