# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

defmodule PutridParrot.Units.BitsPerSecond do
  @moduledoc """
  Bits Per Second conversion functions
  """

  @doc """
  Converts the supplied Bits Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value / 1000.0

  @doc """
  Converts the supplied Bits Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value / 1.0e+6

  @doc """
  Converts the supplied Bits Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value / 1.0e+9

  @doc """
  Converts the supplied Bits Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value / 1.0e+12

  @doc """
  Converts the supplied Bits Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value / 8000.0

  @doc """
  Converts the supplied Bits Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value / 8.0e+6

  @doc """
  Converts the supplied Bits Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value / 8.0e+9

  @doc """
  Converts the supplied Bits Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value / 8.0e+12

  @doc """
  Converts the supplied Bits Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value / 1024.0

  @doc """
  Converts the supplied Bits Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value / 1_048_576.0
end

defmodule PutridParrot.Units.GigaBitsPerSecond do
  @moduledoc """
  GigaBits Per Second conversion functions
  """

  @doc """
  Converts the supplied GigaBits Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 1.0e+9

  @doc """
  Converts the supplied GigaBits Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value * 1.0e+6

  @doc """
  Converts the supplied GigaBits Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value * 1000.0

  @doc """
  Converts the supplied GigaBits Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value / 1000.0

  @doc """
  Converts the supplied GigaBits Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value * 125_000.0

  @doc """
  Converts the supplied GigaBits Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value * 125.0

  @doc """
  Converts the supplied GigaBits Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value / 8.0

  @doc """
  Converts the supplied GigaBits Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value / 8000.0

  @doc """
  Converts the supplied GigaBits Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value * 976_562.5

  @doc """
  Converts the supplied GigaBits Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value * 953.67431640625
end

defmodule PutridParrot.Units.GigaBytesPerSecond do
  @moduledoc """
  GigaBytes Per Second conversion functions
  """

  @doc """
  Converts the supplied GigaBytes Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 8.0e+9

  @doc """
  Converts the supplied GigaBytes Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value * 8.0e+6

  @doc """
  Converts the supplied GigaBytes Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value * 8000.0

  @doc """
  Converts the supplied GigaBytes Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value * 8.0

  @doc """
  Converts the supplied GigaBytes Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value / 125.0

  @doc """
  Converts the supplied GigaBytes Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value * 1.0e+6

  @doc """
  Converts the supplied GigaBytes Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value * 1000.0

  @doc """
  Converts the supplied GigaBytes Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value / 1000.0

  @doc """
  Converts the supplied GigaBytes Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value * 7_812_500.0

  @doc """
  Converts the supplied GigaBytes Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value * 7629.39
end

defmodule PutridParrot.Units.KibibitsPerSecond do
  @moduledoc """
  Kibibits Per Second conversion functions
  """

  @doc """
  Converts the supplied Kibibits Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 1024.0

  @doc """
  Converts the supplied Kibibits Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value * 1.024

  @doc """
  Converts the supplied Kibibits Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value / 976.563

  @doc """
  Converts the supplied Kibibits Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value / 976_562.5

  @doc """
  Converts the supplied Kibibits Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value / 976_562_500.0

  @doc """
  Converts the supplied Kibibits Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value / 7.8125

  @doc """
  Converts the supplied Kibibits Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value / 7812.5

  @doc """
  Converts the supplied Kibibits Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value / 7_812_500.0

  @doc """
  Converts the supplied Kibibits Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value / 7_812_500_000.0

  @doc """
  Converts the supplied Kibibits Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value / 1024.0
end

defmodule PutridParrot.Units.KiloBitsPerSecond do
  @moduledoc """
  KiloBits Per Second conversion functions
  """

  @doc """
  Converts the supplied KiloBits Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 1000.0

  @doc """
  Converts the supplied KiloBits Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value / 1000.0

  @doc """
  Converts the supplied KiloBits Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value / 1.0e+6

  @doc """
  Converts the supplied KiloBits Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value / 1.0e+9

  @doc """
  Converts the supplied KiloBits Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value / 8.0

  @doc """
  Converts the supplied KiloBits Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value / 8000.0

  @doc """
  Converts the supplied KiloBits Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value / 8.0e+6

  @doc """
  Converts the supplied KiloBits Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value / 8.0e+9

  @doc """
  Converts the supplied KiloBits Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value / 1.024

  @doc """
  Converts the supplied KiloBits Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value / 1048.58
end

defmodule PutridParrot.Units.KiloBytesPerSecond do
  @moduledoc """
  KiloBytes Per Second conversion functions
  """

  @doc """
  Converts the supplied KiloBytes Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 8000.0

  @doc """
  Converts the supplied KiloBytes Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value * 8.0

  @doc """
  Converts the supplied KiloBytes Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value / 125.0

  @doc """
  Converts the supplied KiloBytes Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value / 125_000.0

  @doc """
  Converts the supplied KiloBytes Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value / 1.25e+8

  @doc """
  Converts the supplied KiloBytes Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value / 1000.0

  @doc """
  Converts the supplied KiloBytes Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value / 1.0e+6

  @doc """
  Converts the supplied KiloBytes Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value / 1.0e+9

  @doc """
  Converts the supplied KiloBytes Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value * 7.8125

  @doc """
  Converts the supplied KiloBytes Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value * 0.00762939
end

defmodule PutridParrot.Units.MebibitsPerSecond do
  @moduledoc """
  Mebibits Per Second conversion functions
  """

  @doc """
  Converts the supplied Mebibits Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 1_048_576.0

  @doc """
  Converts the supplied Mebibits Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value * 1048.58

  @doc """
  Converts the supplied Mebibits Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value * 1.04858

  @doc """
  Converts the supplied Mebibits Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value / 953.67431640625

  @doc """
  Converts the supplied Mebibits Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value / 953_674.0

  @doc """
  Converts the supplied Mebibits Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value / 0.00762939

  @doc """
  Converts the supplied Mebibits Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value / 7.62939

  @doc """
  Converts the supplied Mebibits Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value / 7629.39

  @doc """
  Converts the supplied Mebibits Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value * 0.000000131072

  @doc """
  Converts the supplied Mebibits Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value * 1024.0
end

defmodule PutridParrot.Units.MegaBitsPerSecond do
  @moduledoc """
  MegaBits Per Second conversion functions
  """

  @doc """
  Converts the supplied MegaBits Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 1.0e+6

  @doc """
  Converts the supplied MegaBits Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value * 1000.0

  @doc """
  Converts the supplied MegaBits Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value / 1000.0

  @doc """
  Converts the supplied MegaBits Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value / 1.0e+6

  @doc """
  Converts the supplied MegaBits Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value * 125.0

  @doc """
  Converts the supplied MegaBits Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value / 8.0

  @doc """
  Converts the supplied MegaBits Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value / 8000.0

  @doc """
  Converts the supplied MegaBits Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value / 8.0e+6

  @doc """
  Converts the supplied MegaBits Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value * 976.563

  @doc """
  Converts the supplied MegaBits Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value / 1.04858
end

defmodule PutridParrot.Units.MegaBytesPerSecond do
  @moduledoc """
  MegaBytes Per Second conversion functions
  """

  @doc """
  Converts the supplied MegaBytes Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 8.0e+6

  @doc """
  Converts the supplied MegaBytes Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value * 8000.0

  @doc """
  Converts the supplied MegaBytes Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value * 8.0

  @doc """
  Converts the supplied MegaBytes Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value / 125.0

  @doc """
  Converts the supplied MegaBytes Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value / 125_000.0

  @doc """
  Converts the supplied MegaBytes Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value * 1000.0

  @doc """
  Converts the supplied MegaBytes Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value / 1000.0

  @doc """
  Converts the supplied MegaBytes Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value / 1.0e+6

  @doc """
  Converts the supplied MegaBytes Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value * 7812.5

  @doc """
  Converts the supplied MegaBytes Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value * 7.62939
end

defmodule PutridParrot.Units.TeraBitsPerSecond do
  @moduledoc """
  TeraBits Per Second conversion functions
  """

  @doc """
  Converts the supplied TeraBits Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 1.0e+12

  @doc """
  Converts the supplied TeraBits Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value * 1.0e+9

  @doc """
  Converts the supplied TeraBits Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value * 1.0e+6

  @doc """
  Converts the supplied TeraBits Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value * 1000.0

  @doc """
  Converts the supplied TeraBits Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value * 1.25e+8

  @doc """
  Converts the supplied TeraBits Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value * 125_000.0

  @doc """
  Converts the supplied TeraBits Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value * 125.0

  @doc """
  Converts the supplied TeraBits Per Second value to TeraBytes Per Second
  """
  def to_tera_bytes_per_second(value), do: value / 8.0

  @doc """
  Converts the supplied TeraBits Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value * 976_562_500.0

  @doc """
  Converts the supplied TeraBits Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value * 953_674.0
end

defmodule PutridParrot.Units.TeraBytesPerSecond do
  @moduledoc """
  TeraBytes Per Second conversion functions
  """

  @doc """
  Converts the supplied TeraBytes Per Second value to Bits Per Second
  """
  def to_bits_per_second(value), do: value * 8.0e+12

  @doc """
  Converts the supplied TeraBytes Per Second value to KiloBits Per Second
  """
  def to_kilo_bits_per_second(value), do: value * 8.0e+9

  @doc """
  Converts the supplied TeraBytes Per Second value to MegaBits Per Second
  """
  def to_mega_bits_per_second(value), do: value * 8.0e+6

  @doc """
  Converts the supplied TeraBytes Per Second value to GigaBits Per Second
  """
  def to_giga_bits_per_second(value), do: value * 8000.0

  @doc """
  Converts the supplied TeraBytes Per Second value to TeraBits Per Second
  """
  def to_tera_bits_per_second(value), do: value * 8.0

  @doc """
  Converts the supplied TeraBytes Per Second value to KiloBytes Per Second
  """
  def to_kilo_bytes_per_second(value), do: value * 1.0e+9

  @doc """
  Converts the supplied TeraBytes Per Second value to MegaBytes Per Second
  """
  def to_mega_bytes_per_second(value), do: value * 1.0e+6

  @doc """
  Converts the supplied TeraBytes Per Second value to GigaBytes Per Second
  """
  def to_giga_bytes_per_second(value), do: value * 1000.0

  @doc """
  Converts the supplied TeraBytes Per Second value to Kibibits Per Second
  """
  def to_kibibits_per_second(value), do: value * 7_812_500_000.0

  @doc """
  Converts the supplied TeraBytes Per Second value to Mebibits Per Second
  """
  def to_mebibits_per_second(value), do: value / 0.000000131072
end
