# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

defmodule PutridParrot.Units.Centimetres do
	@moduledoc """
	Centimetres conversion functions
	"""

	@doc """
	Converts the supplied Centimetres value to Millimetres
	"""
	def to_millimetres(value), do: value * 10.0
	@doc """
	Converts the supplied Centimetres value to Metres
	"""
	def to_metres(value), do: value / 100.0
	@doc """
	Converts the supplied Centimetres value to Kilometres
	"""
	def to_kilometres(value), do: value / 100000.0
	@doc """
	Converts the supplied Centimetres value to Inches
	"""
	def to_inches(value), do: value / 2.54
	@doc """
	Converts the supplied Centimetres value to Feet
	"""
	def to_feet(value), do: value / 30.48
	@doc """
	Converts the supplied Centimetres value to Yards
	"""
	def to_yards(value), do: value / 91.44
	@doc """
	Converts the supplied Centimetres value to Miles
	"""
	def to_miles(value), do: value / 160934.4
	@doc """
	Converts the supplied Centimetres value to Nautical Miles
	"""
	def to_nauticalmiles(value), do: value / 185200.0
end

defmodule PutridParrot.Units.Feet do
	@moduledoc """
	Feet conversion functions
	"""

	@doc """
	Converts the supplied Feet value to Millimetres
	"""
	def to_millimetres(value), do: value * 304.8
	@doc """
	Converts the supplied Feet value to Centimetres
	"""
	def to_centimetres(value), do: value * 30.48
	@doc """
	Converts the supplied Feet value to Metres
	"""
	def to_metres(value), do: value * 0.3048
	@doc """
	Converts the supplied Feet value to Kilometres
	"""
	def to_kilometres(value), do: value * 0.0003048
	@doc """
	Converts the supplied Feet value to Inches
	"""
	def to_inches(value), do: value * 12.0
	@doc """
	Converts the supplied Feet value to Yards
	"""
	def to_yards(value), do: value / 3.0
	@doc """
	Converts the supplied Feet value to Miles
	"""
	def to_miles(value), do: value / 5280.0
	@doc """
	Converts the supplied Feet value to Nautical Miles
	"""
	def to_nauticalmiles(value), do: value / 6076.12
end

defmodule PutridParrot.Units.Inches do
	@moduledoc """
	Inches conversion functions
	"""

	@doc """
	Converts the supplied Inches value to Millimetres
	"""
	def to_millimetres(value), do: value * 25.4
	@doc """
	Converts the supplied Inches value to Centimetres
	"""
	def to_centimetres(value), do: value * 2.54
	@doc """
	Converts the supplied Inches value to Metres
	"""
	def to_metres(value), do: value / 39.37007874
	@doc """
	Converts the supplied Inches value to Kilometres
	"""
	def to_kilometres(value), do: value / 39370.07874
	@doc """
	Converts the supplied Inches value to Feet
	"""
	def to_feet(value), do: value / 12.0
	@doc """
	Converts the supplied Inches value to Yards
	"""
	def to_yards(value), do: value / 36.0
	@doc """
	Converts the supplied Inches value to Miles
	"""
	def to_miles(value), do: value / 63360.0
	@doc """
	Converts the supplied Inches value to Nautical Miles
	"""
	def to_nauticalmiles(value), do: value / 72913.4
end

defmodule PutridParrot.Units.Kilometres do
	@moduledoc """
	Kilometres conversion functions
	"""

	@doc """
	Converts the supplied Kilometres value to Millimetres
	"""
	def to_millimetres(value), do: value * 1000000.0
	@doc """
	Converts the supplied Kilometres value to Centimetres
	"""
	def to_centimetres(value), do: value * 100000.0
	@doc """
	Converts the supplied Kilometres value to Metres
	"""
	def to_metres(value), do: value * 1000.0
	@doc """
	Converts the supplied Kilometres value to Inches
	"""
	def to_inches(value), do: value * 39370.07874
	@doc """
	Converts the supplied Kilometres value to Feet
	"""
	def to_feet(value), do: value / 0.0003048
	@doc """
	Converts the supplied Kilometres value to Yards
	"""
	def to_yards(value), do: value / 0.0009144
	@doc """
	Converts the supplied Kilometres value to Miles
	"""
	def to_miles(value), do: value / 1.609344
	@doc """
	Converts the supplied Kilometres value to Nautical Miles
	"""
	def to_nauticalmiles(value), do: value / 1.85200
end

defmodule PutridParrot.Units.Metres do
	@moduledoc """
	Metres conversion functions
	"""

	@doc """
	Converts the supplied Metres value to Millimetres
	"""
	def to_millimetres(value), do: value * 1000.0
	@doc """
	Converts the supplied Metres value to Centimetres
	"""
	def to_centimetres(value), do: value * 100.0
	@doc """
	Converts the supplied Metres value to Kilometres
	"""
	def to_kilometres(value), do: value / 1000.0
	@doc """
	Converts the supplied Metres value to Inches
	"""
	def to_inches(value), do: value * 39.37007874
	@doc """
	Converts the supplied Metres value to Feet
	"""
	def to_feet(value), do: value / 0.3048
	@doc """
	Converts the supplied Metres value to Yards
	"""
	def to_yards(value), do: value / 0.9144
	@doc """
	Converts the supplied Metres value to Miles
	"""
	def to_miles(value), do: value / 1609.344
	@doc """
	Converts the supplied Metres value to Nautical Miles
	"""
	def to_nauticalmiles(value), do: value / 1852.0
end

defmodule PutridParrot.Units.Miles do
	@moduledoc """
	Miles conversion functions
	"""

	@doc """
	Converts the supplied Miles value to Millimetres
	"""
	def to_millimetres(value), do: value * 1609344.0
	@doc """
	Converts the supplied Miles value to Centimetres
	"""
	def to_centimetres(value), do: value * 160934.4
	@doc """
	Converts the supplied Miles value to Metres
	"""
	def to_metres(value), do: value * 1609.344
	@doc """
	Converts the supplied Miles value to Kilometres
	"""
	def to_kilometres(value), do: value * 1.609344
	@doc """
	Converts the supplied Miles value to Inches
	"""
	def to_inches(value), do: value * 63360.0
	@doc """
	Converts the supplied Miles value to Feet
	"""
	def to_feet(value), do: value * 5280.0
	@doc """
	Converts the supplied Miles value to Yards
	"""
	def to_yards(value), do: value * 1760.0
	@doc """
	Converts the supplied Miles value to Nautical Miles
	"""
	def to_nauticalmiles(value), do: value / 1.15078
end

defmodule PutridParrot.Units.Millimetres do
	@moduledoc """
	Millimetres conversion functions
	"""

	@doc """
	Converts the supplied Millimetres value to Centimetres
	"""
	def to_centimetres(value), do: value / 10.0
	@doc """
	Converts the supplied Millimetres value to Metres
	"""
	def to_metres(value), do: value / 1000.0
	@doc """
	Converts the supplied Millimetres value to Kilometres
	"""
	def to_kilometres(value), do: value / 1000000.0
	@doc """
	Converts the supplied Millimetres value to Inches
	"""
	def to_inches(value), do: value / 25.4
	@doc """
	Converts the supplied Millimetres value to Feet
	"""
	def to_feet(value), do: value / 304.8
	@doc """
	Converts the supplied Millimetres value to Yards
	"""
	def to_yards(value), do: value / 914.4
	@doc """
	Converts the supplied Millimetres value to Miles
	"""
	def to_miles(value), do: value / 1609344.0
	@doc """
	Converts the supplied Millimetres value to Nautical Miles
	"""
	def to_nauticalmiles(value), do: value / 1852000.0
end

defmodule PutridParrot.Units.NauticalMiles do
	@moduledoc """
	Nautical Miles conversion functions
	"""

	@doc """
	Converts the supplied Nautical Miles value to Millimetres
	"""
	def to_millimetres(value), do: value * 1852000.0
	@doc """
	Converts the supplied Nautical Miles value to Centimetres
	"""
	def to_centimetres(value), do: value * 185200.0
	@doc """
	Converts the supplied Nautical Miles value to Metres
	"""
	def to_metres(value), do: value * 1852.0
	@doc """
	Converts the supplied Nautical Miles value to Kilometres
	"""
	def to_kilometres(value), do: value * 1.85200
	@doc """
	Converts the supplied Nautical Miles value to Inches
	"""
	def to_inches(value), do: value * 72913.4
	@doc """
	Converts the supplied Nautical Miles value to Feet
	"""
	def to_feet(value), do: value * 6076.12
	@doc """
	Converts the supplied Nautical Miles value to Yards
	"""
	def to_yards(value), do: value * 2025.37
	@doc """
	Converts the supplied Nautical Miles value to Miles
	"""
	def to_miles(value), do: value * 1.15078
end

defmodule PutridParrot.Units.Yards do
	@moduledoc """
	Yards conversion functions
	"""

	@doc """
	Converts the supplied Yards value to Millimetres
	"""
	def to_millimetres(value), do: value * 914.4
	@doc """
	Converts the supplied Yards value to Centimetres
	"""
	def to_centimetres(value), do: value * 91.44
	@doc """
	Converts the supplied Yards value to Metres
	"""
	def to_metres(value), do: value * 0.9144
	@doc """
	Converts the supplied Yards value to Kilometres
	"""
	def to_kilometres(value), do: value * 0.0009144
	@doc """
	Converts the supplied Yards value to Inches
	"""
	def to_inches(value), do: value * 36.0
	@doc """
	Converts the supplied Yards value to Feet
	"""
	def to_feet(value), do: value * 3.0
	@doc """
	Converts the supplied Yards value to Miles
	"""
	def to_miles(value), do: value / 1760.0
	@doc """
	Converts the supplied Yards value to Nautical Miles
	"""
	def to_nauticalmiles(value), do: value / 2025.37
end
