# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

# LumenHour conversion functions
defmodule PutridParrot.Units.LumenHour do
	# Converts the supplied LumenHour value to Talbot
	def to_talbot(value), do: value * 3600.0
	# Converts the supplied LumenHour value to LumenMinute
	def to_lumenminute(value), do: value * 60.0
	# Converts the supplied LumenHour value to LumenSecond
	def to_lumensecond(value), do: value * 3600.0
end

# LumenMinute conversion functions
defmodule PutridParrot.Units.LumenMinute do
	# Converts the supplied LumenMinute value to Talbot
	def to_talbot(value), do: value * 60.0
	# Converts the supplied LumenMinute value to LumenHour
	def to_lumenhour(value), do: value / 60.0
	# Converts the supplied LumenMinute value to LumenSecond
	def to_lumensecond(value), do: value * 60.0
end

# LumenSecond conversion functions
defmodule PutridParrot.Units.LumenSecond do
	# Converts the supplied LumenSecond value to Talbot
	def to_talbot(value), do: value
	# Converts the supplied LumenSecond value to LumenHour
	def to_lumenhour(value), do: value / 3600.0
	# Converts the supplied LumenSecond value to LumenMinute
	def to_lumenminute(value), do: value / 60.0
end

# Talbot conversion functions
defmodule PutridParrot.Units.Talbot do
	# Converts the supplied Talbot value to LumenSecond
	def to_lumensecond(value), do: value
	# Converts the supplied Talbot value to LumenHour
	def to_lumenhour(value), do: value / 3600.0
	# Converts the supplied Talbot value to LumenMinute
	def to_lumenminute(value), do: value / 60.0
end
