# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

defmodule PutridParrot.Units.Ampereturns do
  @moduledoc """
  Ampere-turns conversion functions
  """

  @doc """
  Converts the supplied Ampere-turns value to Gilberts
  """
  def to_gilberts(value), do: value / 0.7957747154595
end

defmodule PutridParrot.Units.Gilberts do
  @moduledoc """
  Gilberts conversion functions
  """

  @doc """
  Converts the supplied Gilberts value to Ampere-turns
  """
  def to_ampereturns(value), do: value * 0.7957747154595
end
