# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

# Carats conversion functions
defmodule PutridParrot.Units.Carats do
	# Converts the supplied Carats value to Milligrams
	def to_milligrams(value), do: value * 200.0
	# Converts the supplied Carats value to Grams
	def to_grams(value), do: value / 5.0
	# Converts the supplied Carats value to Kilograms
	def to_kilograms(value), do: value / 5000.0
	# Converts the supplied Carats value to Tonnes
	def to_tonnes(value), do: value / 5.0e+6
	# Converts the supplied Carats value to Ounces
	def to_ounces(value), do: value * 0.00705479
	# Converts the supplied Carats value to Pounds
	def to_pounds(value), do: value * 0.000440925
	# Converts the supplied Carats value to Stones
	def to_stones(value), do: value * 3.1495e-5
end

# Grams conversion functions
defmodule PutridParrot.Units.Grams do
	# Converts the supplied Grams value to Milligrams
	def to_milligrams(value), do: value * 1000.0
	# Converts the supplied Grams value to Kilograms
	def to_kilograms(value), do: value / 1000.0
	# Converts the supplied Grams value to Tonnes
	def to_tonnes(value), do: value * 1.0e-6
	# Converts the supplied Grams value to Ounces
	def to_ounces(value), do: value / 28.3495231
	# Converts the supplied Grams value to Pounds
	def to_pounds(value), do: value / 453.59237
	# Converts the supplied Grams value to Stones
	def to_stones(value), do: value / 6350.29318
	# Converts the supplied Grams value to Carats
	def to_carats(value), do: value * 5.0
end

# Kilograms conversion functions
defmodule PutridParrot.Units.Kilograms do
	# Converts the supplied Kilograms value to Milligrams
	def to_milligrams(value), do: value * 1.0e+6
	# Converts the supplied Kilograms value to Grams
	def to_grams(value), do: value * 1000.0
	# Converts the supplied Kilograms value to Tonnes
	def to_tonnes(value), do: value * 0.001
	# Converts the supplied Kilograms value to Ounces
	def to_ounces(value), do: value * 35.274
	# Converts the supplied Kilograms value to Pounds
	def to_pounds(value), do: value * 2.20462
	# Converts the supplied Kilograms value to Stones
	def to_stones(value), do: value / 6.35029
	# Converts the supplied Kilograms value to Carats
	def to_carats(value), do: value * 5000.0
end

# Milligrams conversion functions
defmodule PutridParrot.Units.Milligrams do
	# Converts the supplied Milligrams value to Grams
	def to_grams(value), do: value / 1000.0
	# Converts the supplied Milligrams value to Kilograms
	def to_kilograms(value), do: value / 1.0e+6
	# Converts the supplied Milligrams value to Tonnes
	def to_tonnes(value), do: value / 1.0e+9
	# Converts the supplied Milligrams value to Ounces
	def to_ounces(value), do: value / 28349.5231
	# Converts the supplied Milligrams value to Pounds
	def to_pounds(value), do: value / 453592.37
	# Converts the supplied Milligrams value to Stones
	def to_stones(value), do: value / 6350293.18
	# Converts the supplied Milligrams value to Carats
	def to_carats(value), do: value / 200.0
end

# Ounces conversion functions
defmodule PutridParrot.Units.Ounces do
	# Converts the supplied Ounces value to Milligrams
	def to_milligrams(value), do: value * 28349.5231
	# Converts the supplied Ounces value to Grams
	def to_grams(value), do: value * 28.3495231
	# Converts the supplied Ounces value to Kilograms
	def to_kilograms(value), do: value / 35.274
	# Converts the supplied Ounces value to Tonnes
	def to_tonnes(value), do: value * 0.0000283495231
	# Converts the supplied Ounces value to Pounds
	def to_pounds(value), do: value * 0.0625
	# Converts the supplied Ounces value to Stones
	def to_stones(value), do: value / 224.0
	# Converts the supplied Ounces value to Carats
	def to_carats(value), do: value / 0.00705479
end

# Pounds conversion functions
defmodule PutridParrot.Units.Pounds do
	# Converts the supplied Pounds value to Milligrams
	def to_milligrams(value), do: value * 453592.37
	# Converts the supplied Pounds value to Grams
	def to_grams(value), do: value * 453.59237
	# Converts the supplied Pounds value to Kilograms
	def to_kilograms(value), do: value / 2.20462
	# Converts the supplied Pounds value to Tonnes
	def to_tonnes(value), do: value / 2204.62
	# Converts the supplied Pounds value to Ounces
	def to_ounces(value), do: value * 16.0
	# Converts the supplied Pounds value to Stones
	def to_stones(value), do: value / 14.0
	# Converts the supplied Pounds value to Carats
	def to_carats(value), do: value / 0.000440925
end

# Stones conversion functions
defmodule PutridParrot.Units.Stones do
	# Converts the supplied Stones value to Milligrams
	def to_milligrams(value), do: value * 6350293.18
	# Converts the supplied Stones value to Grams
	def to_grams(value), do: value * 6350.29318
	# Converts the supplied Stones value to Kilograms
	def to_kilograms(value), do: value * 6.35029
	# Converts the supplied Stones value to Tonnes
	def to_tonnes(value), do: value / 157.473
	# Converts the supplied Stones value to Ounces
	def to_ounces(value), do: value * 224.0
	# Converts the supplied Stones value to Pounds
	def to_pounds(value), do: value * 14.0
	# Converts the supplied Stones value to Carats
	def to_carats(value), do: value / 3.1495e-5
end

# Tonnes conversion functions
defmodule PutridParrot.Units.Tonnes do
	# Converts the supplied Tonnes value to Milligrams
	def to_milligrams(value), do: value * 1.0e+9
	# Converts the supplied Tonnes value to Grams
	def to_grams(value), do: value * 1.0e+6
	# Converts the supplied Tonnes value to Kilograms
	def to_kilograms(value), do: value * 1000.0
	# Converts the supplied Tonnes value to Ounces
	def to_ounces(value), do: value / 0.0000283495231
	# Converts the supplied Tonnes value to Pounds
	def to_pounds(value), do: value * 2204.62
	# Converts the supplied Tonnes value to Stones
	def to_stones(value), do: value * 157.473
	# Converts the supplied Tonnes value to Carats
	def to_carats(value), do: value * 5.0e+6
end
