# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

defmodule PutridParrot.Units.Centuries do
	@moduledoc """
	Centuries conversion functions
	"""

	@doc """
	Converts the supplied Centuries value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 3.154e+18
	@doc """
	Converts the supplied Centuries value to Microseconds
	"""
	def to_microseconds(value), do: value * 3.154e+15
	@doc """
	Converts the supplied Centuries value to Milliseconds
	"""
	def to_milliseconds(value), do: value * 3.154e+12
	@doc """
	Converts the supplied Centuries value to Seconds
	"""
	def to_seconds(value), do: value * 3.154e+9
	@doc """
	Converts the supplied Centuries value to Minutes
	"""
	def to_minutes(value), do: value * 5.256e+7
	@doc """
	Converts the supplied Centuries value to Hours
	"""
	def to_hours(value), do: value * 876000.0
	@doc """
	Converts the supplied Centuries value to Days
	"""
	def to_days(value), do: value * 36500.0
	@doc """
	Converts the supplied Centuries value to Weeks
	"""
	def to_weeks(value), do: value * 5214.29
	@doc """
	Converts the supplied Centuries value to Months
	"""
	def to_months(value), do: value * 1200.0
	@doc """
	Converts the supplied Centuries value to Years
	"""
	def to_years(value), do: value * 100.0
	@doc """
	Converts the supplied Centuries value to Decades
	"""
	def to_decades(value), do: value * 10.0
end

defmodule PutridParrot.Units.Days do
	@moduledoc """
	Days conversion functions
	"""

	@doc """
	Converts the supplied Days value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 8.64e+13
	@doc """
	Converts the supplied Days value to Microseconds
	"""
	def to_microseconds(value), do: value * 8.64e+10
	@doc """
	Converts the supplied Days value to Milliseconds
	"""
	def to_milliseconds(value), do: value * 8.64e+7
	@doc """
	Converts the supplied Days value to Seconds
	"""
	def to_seconds(value), do: value * 86400.0
	@doc """
	Converts the supplied Days value to Minutes
	"""
	def to_minutes(value), do: value * 1440.0
	@doc """
	Converts the supplied Days value to Hours
	"""
	def to_hours(value), do: value * 24.0
	@doc """
	Converts the supplied Days value to Weeks
	"""
	def to_weeks(value), do: value / 7.0
	@doc """
	Converts the supplied Days value to Months
	"""
	def to_months(value), do: value / 30.4167
	@doc """
	Converts the supplied Days value to Years
	"""
	def to_years(value), do: value / 365.0
	@doc """
	Converts the supplied Days value to Decades
	"""
	def to_decades(value), do: value / 3650.0
	@doc """
	Converts the supplied Days value to Centuries
	"""
	def to_centuries(value), do: value / 36500.0
end

defmodule PutridParrot.Units.Decades do
	@moduledoc """
	Decades conversion functions
	"""

	@doc """
	Converts the supplied Decades value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 3.154e+17
	@doc """
	Converts the supplied Decades value to Microseconds
	"""
	def to_microseconds(value), do: value * 3.154e+14
	@doc """
	Converts the supplied Decades value to Milliseconds
	"""
	def to_milliseconds(value), do: value * 3.154e+11
	@doc """
	Converts the supplied Decades value to Seconds
	"""
	def to_seconds(value), do: value * 3.154e+8
	@doc """
	Converts the supplied Decades value to Minutes
	"""
	def to_minutes(value), do: value * 5.256e+6
	@doc """
	Converts the supplied Decades value to Hours
	"""
	def to_hours(value), do: value * 87600.0
	@doc """
	Converts the supplied Decades value to Days
	"""
	def to_days(value), do: value * 3650.0
	@doc """
	Converts the supplied Decades value to Weeks
	"""
	def to_weeks(value), do: value * 521.429
	@doc """
	Converts the supplied Decades value to Months
	"""
	def to_months(value), do: value * 120.0
	@doc """
	Converts the supplied Decades value to Years
	"""
	def to_years(value), do: value * 10.0
	@doc """
	Converts the supplied Decades value to Centuries
	"""
	def to_centuries(value), do: value / 10.0
end

defmodule PutridParrot.Units.Hours do
	@moduledoc """
	Hours conversion functions
	"""

	@doc """
	Converts the supplied Hours value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 3.6e+12
	@doc """
	Converts the supplied Hours value to Microseconds
	"""
	def to_microseconds(value), do: value * 3.6e+9
	@doc """
	Converts the supplied Hours value to Milliseconds
	"""
	def to_milliseconds(value), do: value * 3.6e+6
	@doc """
	Converts the supplied Hours value to Seconds
	"""
	def to_seconds(value), do: value * 3600.0
	@doc """
	Converts the supplied Hours value to Minutes
	"""
	def to_minutes(value), do: value * 60.0
	@doc """
	Converts the supplied Hours value to Days
	"""
	def to_days(value), do: value / 24.0
	@doc """
	Converts the supplied Hours value to Weeks
	"""
	def to_weeks(value), do: value / 168.0
	@doc """
	Converts the supplied Hours value to Months
	"""
	def to_months(value), do: value / 730.001
	@doc """
	Converts the supplied Hours value to Years
	"""
	def to_years(value), do: value / 8760.0
	@doc """
	Converts the supplied Hours value to Decades
	"""
	def to_decades(value), do: value / 87600.0
	@doc """
	Converts the supplied Hours value to Centuries
	"""
	def to_centuries(value), do: value / 876000.0
end

defmodule PutridParrot.Units.Microseconds do
	@moduledoc """
	Microseconds conversion functions
	"""

	@doc """
	Converts the supplied Microseconds value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 1000.0
	@doc """
	Converts the supplied Microseconds value to Milliseconds
	"""
	def to_milliseconds(value), do: value / 1000.0
	@doc """
	Converts the supplied Microseconds value to Seconds
	"""
	def to_seconds(value), do: value / 1.0e+6
	@doc """
	Converts the supplied Microseconds value to Minutes
	"""
	def to_minutes(value), do: value / 6.0e+7
	@doc """
	Converts the supplied Microseconds value to Hours
	"""
	def to_hours(value), do: value / 3.6e+9
	@doc """
	Converts the supplied Microseconds value to Days
	"""
	def to_days(value), do: value / 8.64e+10
	@doc """
	Converts the supplied Microseconds value to Weeks
	"""
	def to_weeks(value), do: value / 6.048e+11
	@doc """
	Converts the supplied Microseconds value to Months
	"""
	def to_months(value), do: value / 2629746000000.0
	@doc """
	Converts the supplied Microseconds value to Years
	"""
	def to_years(value), do: value / 3.154e+13
	@doc """
	Converts the supplied Microseconds value to Decades
	"""
	def to_decades(value), do: value / 3.154e+14
	@doc """
	Converts the supplied Microseconds value to Centuries
	"""
	def to_centuries(value), do: value / 3.154e+15
end

defmodule PutridParrot.Units.Milliseconds do
	@moduledoc """
	Milliseconds conversion functions
	"""

	@doc """
	Converts the supplied Milliseconds value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 1.0e+6
	@doc """
	Converts the supplied Milliseconds value to Microseconds
	"""
	def to_microseconds(value), do: value * 1000.0
	@doc """
	Converts the supplied Milliseconds value to Seconds
	"""
	def to_seconds(value), do: value / 1000.0
	@doc """
	Converts the supplied Milliseconds value to Minutes
	"""
	def to_minutes(value), do: value / 60000.0
	@doc """
	Converts the supplied Milliseconds value to Hours
	"""
	def to_hours(value), do: value / 3.6e+6
	@doc """
	Converts the supplied Milliseconds value to Days
	"""
	def to_days(value), do: value / 8.64e+7
	@doc """
	Converts the supplied Milliseconds value to Weeks
	"""
	def to_weeks(value), do: value / 6.048e+8
	@doc """
	Converts the supplied Milliseconds value to Months
	"""
	def to_months(value), do: value / 2629746000.0
	@doc """
	Converts the supplied Milliseconds value to Years
	"""
	def to_years(value), do: value / 31556952000.0
	@doc """
	Converts the supplied Milliseconds value to Decades
	"""
	def to_decades(value), do: value / 3.154e+11
	@doc """
	Converts the supplied Milliseconds value to Centuries
	"""
	def to_centuries(value), do: value / 3.154e+12
end

defmodule PutridParrot.Units.Minutes do
	@moduledoc """
	Minutes conversion functions
	"""

	@doc """
	Converts the supplied Minutes value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 6.0e+10
	@doc """
	Converts the supplied Minutes value to Microseconds
	"""
	def to_microseconds(value), do: value * 6.0e+7
	@doc """
	Converts the supplied Minutes value to Milliseconds
	"""
	def to_milliseconds(value), do: value * 60000.0
	@doc """
	Converts the supplied Minutes value to Seconds
	"""
	def to_seconds(value), do: value * 60.0
	@doc """
	Converts the supplied Minutes value to Hours
	"""
	def to_hours(value), do: value / 60.0
	@doc """
	Converts the supplied Minutes value to Days
	"""
	def to_days(value), do: value / 1440.0
	@doc """
	Converts the supplied Minutes value to Weeks
	"""
	def to_weeks(value), do: value / 10080.0
	@doc """
	Converts the supplied Minutes value to Months
	"""
	def to_months(value), do: value / 43800.0
	@doc """
	Converts the supplied Minutes value to Years
	"""
	def to_years(value), do: value / 525600.0
	@doc """
	Converts the supplied Minutes value to Decades
	"""
	def to_decades(value), do: value / 5.256e+6
	@doc """
	Converts the supplied Minutes value to Centuries
	"""
	def to_centuries(value), do: value / 5.256e+7
end

defmodule PutridParrot.Units.Months do
	@moduledoc """
	Months conversion functions
	"""

	@doc """
	Converts the supplied Months value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 2629746000000000.0
	@doc """
	Converts the supplied Months value to Microseconds
	"""
	def to_microseconds(value), do: value * 2629746000000.0
	@doc """
	Converts the supplied Months value to Milliseconds
	"""
	def to_milliseconds(value), do: value * 2629746000.0
	@doc """
	Converts the supplied Months value to Seconds
	"""
	def to_seconds(value), do: value * 2.628e+6
	@doc """
	Converts the supplied Months value to Minutes
	"""
	def to_minutes(value), do: value * 43800.0
	@doc """
	Converts the supplied Months value to Hours
	"""
	def to_hours(value), do: value * 730.001
	@doc """
	Converts the supplied Months value to Days
	"""
	def to_days(value), do: value * 30.4167
	@doc """
	Converts the supplied Months value to Weeks
	"""
	def to_weeks(value), do: value * 4.34524
	@doc """
	Converts the supplied Months value to Years
	"""
	def to_years(value), do: value / 12.0
	@doc """
	Converts the supplied Months value to Decades
	"""
	def to_decades(value), do: value / 120.0
	@doc """
	Converts the supplied Months value to Centuries
	"""
	def to_centuries(value), do: value / 1200.0
end

defmodule PutridParrot.Units.Nanoseconds do
	@moduledoc """
	Nanoseconds conversion functions
	"""

	@doc """
	Converts the supplied Nanoseconds value to Microseconds
	"""
	def to_microseconds(value), do: value / 1000.0
	@doc """
	Converts the supplied Nanoseconds value to Milliseconds
	"""
	def to_milliseconds(value), do: value / 1.0e+6
	@doc """
	Converts the supplied Nanoseconds value to Seconds
	"""
	def to_seconds(value), do: value / 1.0e+9
	@doc """
	Converts the supplied Nanoseconds value to Minutes
	"""
	def to_minutes(value), do: value / 6.0e+10
	@doc """
	Converts the supplied Nanoseconds value to Hours
	"""
	def to_hours(value), do: value / 3.6e+12
	@doc """
	Converts the supplied Nanoseconds value to Days
	"""
	def to_days(value), do: value / 8.64e+13
	@doc """
	Converts the supplied Nanoseconds value to Weeks
	"""
	def to_weeks(value), do: value / 6.048e+14
	@doc """
	Converts the supplied Nanoseconds value to Months
	"""
	def to_months(value), do: value / 2629746000000000.0
	@doc """
	Converts the supplied Nanoseconds value to Years
	"""
	def to_years(value), do: value / 3.154e+16
	@doc """
	Converts the supplied Nanoseconds value to Decades
	"""
	def to_decades(value), do: value / 3.154e+17
	@doc """
	Converts the supplied Nanoseconds value to Centuries
	"""
	def to_centuries(value), do: value / 3.154e+18
end

defmodule PutridParrot.Units.Seconds do
	@moduledoc """
	Seconds conversion functions
	"""

	@doc """
	Converts the supplied Seconds value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 1.0e+9
	@doc """
	Converts the supplied Seconds value to Microseconds
	"""
	def to_microseconds(value), do: value * 1.0e+6
	@doc """
	Converts the supplied Seconds value to Milliseconds
	"""
	def to_milliseconds(value), do: value * 1000.0
	@doc """
	Converts the supplied Seconds value to Minutes
	"""
	def to_minutes(value), do: value / 60.0
	@doc """
	Converts the supplied Seconds value to Hours
	"""
	def to_hours(value), do: value / 3600.0
	@doc """
	Converts the supplied Seconds value to Days
	"""
	def to_days(value), do: value / 86400.0
	@doc """
	Converts the supplied Seconds value to Weeks
	"""
	def to_weeks(value), do: value / 604800.0
	@doc """
	Converts the supplied Seconds value to Months
	"""
	def to_months(value), do: value / 2.628e+6
	@doc """
	Converts the supplied Seconds value to Years
	"""
	def to_years(value), do: value / 3.1536e+7
	@doc """
	Converts the supplied Seconds value to Decades
	"""
	def to_decades(value), do: value / 3.154e+8
	@doc """
	Converts the supplied Seconds value to Centuries
	"""
	def to_centuries(value), do: value / 3.154e+9
end

defmodule PutridParrot.Units.Weeks do
	@moduledoc """
	Weeks conversion functions
	"""

	@doc """
	Converts the supplied Weeks value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 6.048e+14
	@doc """
	Converts the supplied Weeks value to Microseconds
	"""
	def to_microseconds(value), do: value * 6.048e+11
	@doc """
	Converts the supplied Weeks value to Milliseconds
	"""
	def to_milliseconds(value), do: value * 6.048e+8
	@doc """
	Converts the supplied Weeks value to Seconds
	"""
	def to_seconds(value), do: value * 604800.0
	@doc """
	Converts the supplied Weeks value to Minutes
	"""
	def to_minutes(value), do: value * 10080.0
	@doc """
	Converts the supplied Weeks value to Hours
	"""
	def to_hours(value), do: value * 168.0
	@doc """
	Converts the supplied Weeks value to Days
	"""
	def to_days(value), do: value * 7.0
	@doc """
	Converts the supplied Weeks value to Months
	"""
	def to_months(value), do: value / 4.34524
	@doc """
	Converts the supplied Weeks value to Years
	"""
	def to_years(value), do: value / 52.143
	@doc """
	Converts the supplied Weeks value to Decades
	"""
	def to_decades(value), do: value / 521.429
	@doc """
	Converts the supplied Weeks value to Centuries
	"""
	def to_centuries(value), do: value / 5214.29
end

defmodule PutridParrot.Units.Years do
	@moduledoc """
	Years conversion functions
	"""

	@doc """
	Converts the supplied Years value to Nanoseconds
	"""
	def to_nanoseconds(value), do: value * 3.154e+16
	@doc """
	Converts the supplied Years value to Microseconds
	"""
	def to_microseconds(value), do: value * 3.154e+13
	@doc """
	Converts the supplied Years value to Milliseconds
	"""
	def to_milliseconds(value), do: value * 31556952000.0
	@doc """
	Converts the supplied Years value to Seconds
	"""
	def to_seconds(value), do: value * 3.1536e+7
	@doc """
	Converts the supplied Years value to Minutes
	"""
	def to_minutes(value), do: value * 525600.0
	@doc """
	Converts the supplied Years value to Hours
	"""
	def to_hours(value), do: value * 8760.0
	@doc """
	Converts the supplied Years value to Days
	"""
	def to_days(value), do: value * 365.0
	@doc """
	Converts the supplied Years value to Weeks
	"""
	def to_weeks(value), do: value * 52.143
	@doc """
	Converts the supplied Years value to Months
	"""
	def to_months(value), do: value * 12.0
	@doc """
	Converts the supplied Years value to Decades
	"""
	def to_decades(value), do: value / 10.0
	@doc """
	Converts the supplied Years value to Centuries
	"""
	def to_centuries(value), do: value / 100.0
end
