# <auto-generated>
# This code was generated by the UnitCodeGenerator tool
#
# Changes to this file will be lost if the code is regenerated
# </auto-generated>

# Cubic Feet conversion functions
defmodule PutridParrot.Units.CubicFeet do
	# Converts the supplied Cubic Feet value to Millilitres
	def to_millilitres(value), do: value * 28316.8
	# Converts the supplied Cubic Feet value to Litres
	def to_litres(value), do: value * 28.3168
	# Converts the supplied Cubic Feet value to Kilolitres
	def to_kilolitres(value), do: value / 35.3147
	# Converts the supplied Cubic Feet value to Teaspoons
	def to_teaspoons(value), do: value * 4783.74
	# Converts the supplied Cubic Feet value to Tablespoons
	def to_tablespoons(value), do: value * 1594.58
	# Converts the supplied Cubic Feet value to Quarts
	def to_quarts(value), do: value * 24.9153
	# Converts the supplied Cubic Feet value to Pints
	def to_pints(value), do: value * 49.8307
	# Converts the supplied Cubic Feet value to Gallons
	def to_gallons(value), do: value * 6.22884
	# Converts the supplied Cubic Feet value to Fluid Ounces
	def to_fluidounces(value), do: value * 996.614
	# Converts the supplied Cubic Feet value to US Teaspoons
	def to_usteaspoons(value), do: value * 5745.04
	# Converts the supplied Cubic Feet value to US Tablespoons
	def to_ustablespoons(value), do: value * 1915.01
	# Converts the supplied Cubic Feet value to US Quarts
	def to_usquarts(value), do: value * 29.9221
	# Converts the supplied Cubic Feet value to US Pints
	def to_uspints(value), do: value * 59.8442
	# Converts the supplied Cubic Feet value to US Gallons
	def to_usgallons(value), do: value * 7.48052
	# Converts the supplied Cubic Feet value to US Fluid Ounces
	def to_usfluidounces(value), do: value * 957.506
	# Converts the supplied Cubic Feet value to US Cups
	def to_uscups(value), do: value * 117.987
	# Converts the supplied Cubic Feet value to Cubic Metres
	def to_cubicmetres(value), do: value / 35.3147
	# Converts the supplied Cubic Feet value to Cubic Inches
	def to_cubicinches(value), do: value * 1728.0
	# Converts the supplied Cubic Feet value to Oil Barrels
	def to_oilbarrels(value), do: value / 5.61458
end

# Cubic Inches conversion functions
defmodule PutridParrot.Units.CubicInches do
	# Converts the supplied Cubic Inches value to Millilitres
	def to_millilitres(value), do: value * 16.3871
	# Converts the supplied Cubic Inches value to Litres
	def to_litres(value), do: value / 61.0237
	# Converts the supplied Cubic Inches value to Kilolitres
	def to_kilolitres(value), do: value / 61023.7
	# Converts the supplied Cubic Inches value to Teaspoons
	def to_teaspoons(value), do: value * 2.76837
	# Converts the supplied Cubic Inches value to Tablespoons
	def to_tablespoons(value), do: value / 1.08367
	# Converts the supplied Cubic Inches value to Quarts
	def to_quarts(value), do: value / 69.3549
	# Converts the supplied Cubic Inches value to Pints
	def to_pints(value), do: value / 34.6774
	# Converts the supplied Cubic Inches value to Gallons
	def to_gallons(value), do: value / 277.419
	# Converts the supplied Cubic Inches value to Fluid Ounces
	def to_fluidounces(value), do: value / 1.73387
	# Converts the supplied Cubic Inches value to US Teaspoons
	def to_usteaspoons(value), do: value * 3.32468
	# Converts the supplied Cubic Inches value to US Tablespoons
	def to_ustablespoons(value), do: value * 1.10823
	# Converts the supplied Cubic Inches value to US Quarts
	def to_usquarts(value), do: value / 57.75
	# Converts the supplied Cubic Inches value to US Pints
	def to_uspints(value), do: value / 28.875
	# Converts the supplied Cubic Inches value to US Gallons
	def to_usgallons(value), do: value / 231.0
	# Converts the supplied Cubic Inches value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 1.80469
	# Converts the supplied Cubic Inches value to US Cups
	def to_uscups(value), do: value / 14.6457
	# Converts the supplied Cubic Inches value to Cubic Metres
	def to_cubicmetres(value), do: value / 61023.7
	# Converts the supplied Cubic Inches value to Cubic Feet
	def to_cubicfeet(value), do: value / 1728.0
	# Converts the supplied Cubic Inches value to Oil Barrels
	def to_oilbarrels(value), do: value / 9702.0
end

# Cubic Metres conversion functions
defmodule PutridParrot.Units.CubicMetres do
	# Converts the supplied Cubic Metres value to Millilitres
	def to_millilitres(value), do: value * 1000000.0
	# Converts the supplied Cubic Metres value to Litres
	def to_litres(value), do: value * 1000.0
	# Converts the supplied Cubic Metres value to Kilolitres
	def to_kilolitres(value), do: value * 1.0
	# Converts the supplied Cubic Metres value to Teaspoons
	def to_teaspoons(value), do: value * 168936.0
	# Converts the supplied Cubic Metres value to Tablespoons
	def to_tablespoons(value), do: value * 56312.1
	# Converts the supplied Cubic Metres value to Quarts
	def to_quarts(value), do: value * 879.877
	# Converts the supplied Cubic Metres value to Pints
	def to_pints(value), do: value * 1759.75
	# Converts the supplied Cubic Metres value to Gallons
	def to_gallons(value), do: value * 219.969
	# Converts the supplied Cubic Metres value to Fluid Ounces
	def to_fluidounces(value), do: value * 35195.1
	# Converts the supplied Cubic Metres value to US Teaspoons
	def to_usteaspoons(value), do: value * 202884.0
	# Converts the supplied Cubic Metres value to US Tablespoons
	def to_ustablespoons(value), do: value * 67628.0
	# Converts the supplied Cubic Metres value to US Quarts
	def to_usquarts(value), do: value * 1056.69
	# Converts the supplied Cubic Metres value to US Pints
	def to_uspints(value), do: value * 2113.38
	# Converts the supplied Cubic Metres value to US Gallons
	def to_usgallons(value), do: value * 264.172
	# Converts the supplied Cubic Metres value to US Fluid Ounces
	def to_usfluidounces(value), do: value * 33814.0
	# Converts the supplied Cubic Metres value to US Cups
	def to_uscups(value), do: value * 4166.67
	# Converts the supplied Cubic Metres value to Cubic Feet
	def to_cubicfeet(value), do: value * 35.3147
	# Converts the supplied Cubic Metres value to Cubic Inches
	def to_cubicinches(value), do: value * 61023.7
	# Converts the supplied Cubic Metres value to Oil Barrels
	def to_oilbarrels(value), do: value * 6.28981
end

# Fluid Ounces conversion functions
defmodule PutridParrot.Units.FluidOunces do
	# Converts the supplied Fluid Ounces value to Millilitres
	def to_millilitres(value), do: value * 28.413074243749994496
	# Converts the supplied Fluid Ounces value to Litres
	def to_litres(value), do: value * 0.028413074243749994496
	# Converts the supplied Fluid Ounces value to Kilolitres
	def to_kilolitres(value), do: value * 0.000028413074243749994
	# Converts the supplied Fluid Ounces value to Teaspoons
	def to_teaspoons(value), do: value * 4.8
	# Converts the supplied Fluid Ounces value to Tablespoons
	def to_tablespoons(value), do: value * 1.6
	# Converts the supplied Fluid Ounces value to Quarts
	def to_quarts(value), do: value / 40.0
	# Converts the supplied Fluid Ounces value to Pints
	def to_pints(value), do: value / 20.0
	# Converts the supplied Fluid Ounces value to Gallons
	def to_gallons(value), do: value / 160.0
	# Converts the supplied Fluid Ounces value to US Teaspoons
	def to_usteaspoons(value), do: value / 0.1734737167638313984
	# Converts the supplied Fluid Ounces value to US Tablespoons
	def to_ustablespoons(value), do: value / 0.52042115029149417472
	# Converts the supplied Fluid Ounces value to US Quarts
	def to_usquarts(value), do: value / 33.306953618655629312
	# Converts the supplied Fluid Ounces value to US Pints
	def to_uspints(value), do: value / 16.653476809327814656
	# Converts the supplied Fluid Ounces value to US Gallons
	def to_usgallons(value), do: value / 133.22781447462252544
	# Converts the supplied Fluid Ounces value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 1.0408423005829883904
	# Converts the supplied Fluid Ounces value to US Cups
	def to_uscups(value), do: value / 8.3267384046639071232
	# Converts the supplied Fluid Ounces value to Cubic Metres
	def to_cubicmetres(value), do: value / 35195.1
	# Converts the supplied Fluid Ounces value to Cubic Feet
	def to_cubicfeet(value), do: value / 996.614
	# Converts the supplied Fluid Ounces value to Cubic Inches
	def to_cubicinches(value), do: value * 1.73387
	# Converts the supplied Fluid Ounces value to Oil Barrels
	def to_oilbarrels(value), do: value / 5595.57
end

# Gallons conversion functions
defmodule PutridParrot.Units.Gallons do
	# Converts the supplied Gallons value to Millilitres
	def to_millilitres(value), do: value * 4546.091879
	# Converts the supplied Gallons value to Litres
	def to_litres(value), do: value * 4.546091879
	# Converts the supplied Gallons value to Kilolitres
	def to_kilolitres(value), do: value * 0.0045460918799
	# Converts the supplied Gallons value to Teaspoons
	def to_teaspoons(value), do: value * 768.0
	# Converts the supplied Gallons value to Tablespoons
	def to_tablespoons(value), do: value * 256.0
	# Converts the supplied Gallons value to Quarts
	def to_quarts(value), do: value * 4.0
	# Converts the supplied Gallons value to Pints
	def to_pints(value), do: value * 8.0
	# Converts the supplied Gallons value to Fluid Ounces
	def to_fluidounces(value), do: value * 160.0
	# Converts the supplied Gallons value to US Teaspoons
	def to_usteaspoons(value), do: value / 0.00108421072977394606
	# Converts the supplied Gallons value to US Tablespoons
	def to_ustablespoons(value), do: value / 0.003252632189321838592
	# Converts the supplied Gallons value to US Quarts
	def to_usquarts(value), do: value / 0.20816846011659767808
	# Converts the supplied Gallons value to US Pints
	def to_uspints(value), do: value / 0.10408423005829883904
	# Converts the supplied Gallons value to US Gallons
	def to_usgallons(value), do: value / 0.83267384046639071232
	# Converts the supplied Gallons value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 0.006505264378643677184
	# Converts the supplied Gallons value to US Cups
	def to_uscups(value), do: value / 0.052042115029149417472
	# Converts the supplied Gallons value to Cubic Metres
	def to_cubicmetres(value), do: value / 219.969
	# Converts the supplied Gallons value to Cubic Feet
	def to_cubicfeet(value), do: value / 6.22884
	# Converts the supplied Gallons value to Cubic Inches
	def to_cubicinches(value), do: value * 277.419
	# Converts the supplied Gallons value to Oil Barrels
	def to_oilbarrels(value), do: value / 34.9723
end

# Kilolitres conversion functions
defmodule PutridParrot.Units.Kilolitres do
	# Converts the supplied Kilolitres value to Millilitres
	def to_millilitres(value), do: value * 1000000.0
	# Converts the supplied Kilolitres value to Litres
	def to_litres(value), do: value * 1000.0
	# Converts the supplied Kilolitres value to Teaspoons
	def to_teaspoons(value), do: value / 0.000005919390467447916
	# Converts the supplied Kilolitres value to Tablespoons
	def to_tablespoons(value), do: value / 0.000017758171402343747
	# Converts the supplied Kilolitres value to Quarts
	def to_quarts(value), do: value / 0.00113652296975
	# Converts the supplied Kilolitres value to Pints
	def to_pints(value), do: value / 0.000568261484874999889
	# Converts the supplied Kilolitres value to Gallons
	def to_gallons(value), do: value / 0.0045460918799
	# Converts the supplied Kilolitres value to Fluid Ounces
	def to_fluidounces(value), do: value / 0.0000284130742437499946
	# Converts the supplied Kilolitres value to US Teaspoons
	def to_usteaspoons(value), do: value / 0.000004928921593749999
	# Converts the supplied Kilolitres value to US Tablespoons
	def to_ustablespoons(value), do: value / 0.000014786764781249998
	# Converts the supplied Kilolitres value to US Quarts
	def to_usquarts(value), do: value / 0.000946352945999999959
	# Converts the supplied Kilolitres value to US Pints
	def to_uspints(value), do: value / 0.000473176472999999979
	# Converts the supplied Kilolitres value to US Gallons
	def to_usgallons(value), do: value / 0.003785411784
	# Converts the supplied Kilolitres value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 0.0000295735296
	# Converts the supplied Kilolitres value to US Cups
	def to_uscups(value), do: value / 0.000236588236499999989
	# Converts the supplied Kilolitres value to Cubic Metres
	def to_cubicmetres(value), do: value * 1.0
	# Converts the supplied Kilolitres value to Cubic Feet
	def to_cubicfeet(value), do: value * 35.3147
	# Converts the supplied Kilolitres value to Cubic Inches
	def to_cubicinches(value), do: value * 61023.7
	# Converts the supplied Kilolitres value to Oil Barrels
	def to_oilbarrels(value), do: value * 6.28981
end

# Litres conversion functions
defmodule PutridParrot.Units.Litres do
	# Converts the supplied Litres value to Millilitres
	def to_millilitres(value), do: value * 1000.0
	# Converts the supplied Litres value to Kilolitres
	def to_kilolitres(value), do: value / 1000.0
	# Converts the supplied Litres value to Teaspoons
	def to_teaspoons(value), do: value / 0.005919390467447916134
	# Converts the supplied Litres value to Tablespoons
	def to_tablespoons(value), do: value / 0.017758171402343747584
	# Converts the supplied Litres value to Quarts
	def to_quarts(value), do: value / 1.13652296975
	# Converts the supplied Litres value to Pints
	def to_pints(value), do: value / 0.56826148487499988992
	# Converts the supplied Litres value to Gallons
	def to_gallons(value), do: value / 4.546091879
	# Converts the supplied Litres value to Fluid Ounces
	def to_fluidounces(value), do: value / 0.028413074243749994496
	# Converts the supplied Litres value to US Teaspoons
	def to_usteaspoons(value), do: value / 0.004928921593749999616
	# Converts the supplied Litres value to US Tablespoons
	def to_ustablespoons(value), do: value / 0.014786764781249998848
	# Converts the supplied Litres value to US Quarts
	def to_usquarts(value), do: value / 0.94635294599999995904
	# Converts the supplied Litres value to US Pints
	def to_uspints(value), do: value / 0.47317647299999997952
	# Converts the supplied Litres value to US Gallons
	def to_usgallons(value), do: value / 3.785411784
	# Converts the supplied Litres value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 0.029573529562499997696
	# Converts the supplied Litres value to US Cups
	def to_uscups(value), do: value / 0.23658823649999998976
	# Converts the supplied Litres value to Cubic Metres
	def to_cubicmetres(value), do: value / 1000.0
	# Converts the supplied Litres value to Cubic Feet
	def to_cubicfeet(value), do: value / 28.3168
	# Converts the supplied Litres value to Cubic Inches
	def to_cubicinches(value), do: value * 61.0237
	# Converts the supplied Litres value to Oil Barrels
	def to_oilbarrels(value), do: value / 158.987
end

# Millilitres conversion functions
defmodule PutridParrot.Units.Millilitres do
	# Converts the supplied Millilitres value to Litres
	def to_litres(value), do: value / 1000.0
	# Converts the supplied Millilitres value to Kilolitres
	def to_kilolitres(value), do: value / 1000000.0
	# Converts the supplied Millilitres value to Teaspoons
	def to_teaspoons(value), do: value / 5.9193904674479161344
	# Converts the supplied Millilitres value to Tablespoons
	def to_tablespoons(value), do: value / 17.758171402343747584
	# Converts the supplied Millilitres value to Quarts
	def to_quarts(value), do: value / 1136.52296975
	# Converts the supplied Millilitres value to Pints
	def to_pints(value), do: value / 568.26148487499988992
	# Converts the supplied Millilitres value to Gallons
	def to_gallons(value), do: value / 4546.091879
	# Converts the supplied Millilitres value to Fluid Ounces
	def to_fluidounces(value), do: value / 28.413074243749994496
	# Converts the supplied Millilitres value to US Teaspoons
	def to_usteaspoons(value), do: value / 4.928921593749999616
	# Converts the supplied Millilitres value to US Tablespoons
	def to_ustablespoons(value), do: value / 14.786764781249998848
	# Converts the supplied Millilitres value to US Quarts
	def to_usquarts(value), do: value / 946.35294599999995904
	# Converts the supplied Millilitres value to US Pints
	def to_uspints(value), do: value / 473.17647299999997952
	# Converts the supplied Millilitres value to US Gallons
	def to_usgallons(value), do: value / 3785.411784
	# Converts the supplied Millilitres value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 29.573529562499997696
	# Converts the supplied Millilitres value to US Cups
	def to_uscups(value), do: value / 236.58823649999998976
	# Converts the supplied Millilitres value to Cubic Metres
	def to_cubicmetres(value), do: value / 1000000.0
	# Converts the supplied Millilitres value to Cubic Feet
	def to_cubicfeet(value), do: value / 28316.8
	# Converts the supplied Millilitres value to Cubic Inches
	def to_cubicinches(value), do: value / 16.3871
	# Converts the supplied Millilitres value to Oil Barrels
	def to_oilbarrels(value), do: value / 158987.0
end

# Oil Barrels conversion functions
defmodule PutridParrot.Units.OilBarrels do
	# Converts the supplied Oil Barrels value to Millilitres
	def to_millilitres(value), do: value * 158987.0
	# Converts the supplied Oil Barrels value to Litres
	def to_litres(value), do: value * 158.987
	# Converts the supplied Oil Barrels value to Kilolitres
	def to_kilolitres(value), do: value / 6.28981
	# Converts the supplied Oil Barrels value to Teaspoons
	def to_teaspoons(value), do: value * 26858.7
	# Converts the supplied Oil Barrels value to Tablespoons
	def to_tablespoons(value), do: value * 8952.91
	# Converts the supplied Oil Barrels value to Quarts
	def to_quarts(value), do: value * 139.889
	# Converts the supplied Oil Barrels value to Pints
	def to_pints(value), do: value * 279.779
	# Converts the supplied Oil Barrels value to Gallons
	def to_gallons(value), do: value * 34.9723
	# Converts the supplied Oil Barrels value to Fluid Ounces
	def to_fluidounces(value), do: value * 5595.57
	# Converts the supplied Oil Barrels value to US Teaspoons
	def to_usteaspoons(value), do: value * 32256.0
	# Converts the supplied Oil Barrels value to US Tablespoons
	def to_ustablespoons(value), do: value * 10752.0
	# Converts the supplied Oil Barrels value to US Quarts
	def to_usquarts(value), do: value * 168.0
	# Converts the supplied Oil Barrels value to US Pints
	def to_uspints(value), do: value * 336.0
	# Converts the supplied Oil Barrels value to US Gallons
	def to_usgallons(value), do: value * 42.0
	# Converts the supplied Oil Barrels value to US Fluid Ounces
	def to_usfluidounces(value), do: value * 5376.0
	# Converts the supplied Oil Barrels value to US Cups
	def to_uscups(value), do: value * 662.447
	# Converts the supplied Oil Barrels value to Cubic Metres
	def to_cubicmetres(value), do: value / 6.28981
	# Converts the supplied Oil Barrels value to Cubic Feet
	def to_cubicfeet(value), do: value * 5.61458
	# Converts the supplied Oil Barrels value to Cubic Inches
	def to_cubicinches(value), do: value * 9702.0
end

# Pints conversion functions
defmodule PutridParrot.Units.Pints do
	# Converts the supplied Pints value to Millilitres
	def to_millilitres(value), do: value * 568.26148487499988992
	# Converts the supplied Pints value to Litres
	def to_litres(value), do: value * 0.56826148487499988992
	# Converts the supplied Pints value to Kilolitres
	def to_kilolitres(value), do: value * 0.000568261484874999889
	# Converts the supplied Pints value to Teaspoons
	def to_teaspoons(value), do: value * 96.0
	# Converts the supplied Pints value to Tablespoons
	def to_tablespoons(value), do: value * 32.0
	# Converts the supplied Pints value to Quarts
	def to_quarts(value), do: value  / 2.0
	# Converts the supplied Pints value to Gallons
	def to_gallons(value), do: value / 8.0
	# Converts the supplied Pints value to Fluid Ounces
	def to_fluidounces(value), do: value * 20.0
	# Converts the supplied Pints value to US Teaspoons
	def to_usteaspoons(value), do: value / 0.008673685838191568486
	# Converts the supplied Pints value to US Tablespoons
	def to_ustablespoons(value), do: value / 0.026021057514574708736
	# Converts the supplied Pints value to US Quarts
	def to_usquarts(value), do: value / 1.6653476809327814656
	# Converts the supplied Pints value to US Pints
	def to_uspints(value), do: value / 0.83267384046639071232
	# Converts the supplied Pints value to US Gallons
	def to_usgallons(value), do: value / 6.6613907237311258624
	# Converts the supplied Pints value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 0.052042115029149417472
	# Converts the supplied Pints value to US Cups
	def to_uscups(value), do: value / 0.41633692023319535616
	# Converts the supplied Pints value to Cubic Metres
	def to_cubicmetres(value), do: value / 1759.75
	# Converts the supplied Pints value to Cubic Feet
	def to_cubicfeet(value), do: value / 49.8307
	# Converts the supplied Pints value to Cubic Inches
	def to_cubicinches(value), do: value * 34.6774
	# Converts the supplied Pints value to Oil Barrels
	def to_oilbarrels(value), do: value / 279.779
end

# Quarts conversion functions
defmodule PutridParrot.Units.Quarts do
	# Converts the supplied Quarts value to Millilitres
	def to_millilitres(value), do: value * 1136.52296975
	# Converts the supplied Quarts value to Litres
	def to_litres(value), do: value * 1.13652296975
	# Converts the supplied Quarts value to Kilolitres
	def to_kilolitres(value), do: value * 0.00113652296975
	# Converts the supplied Quarts value to Teaspoons
	def to_teaspoons(value), do: value * 192.0
	# Converts the supplied Quarts value to Tablespoons
	def to_tablespoons(value), do: value * 64.0
	# Converts the supplied Quarts value to Pints
	def to_pints(value), do: value * 2.0
	# Converts the supplied Quarts value to Gallons
	def to_gallons(value), do: value / 4.0
	# Converts the supplied Quarts value to Fluid Ounces
	def to_fluidounces(value), do: value * 40.0
	# Converts the supplied Quarts value to US Teaspoons
	def to_usteaspoons(value), do: value / 0.004336842919095784243
	# Converts the supplied Quarts value to US Tablespoons
	def to_ustablespoons(value), do: value / 0.013010528757287354368
	# Converts the supplied Quarts value to US Quarts
	def to_usquarts(value), do: value / 0.83267384046639071232
	# Converts the supplied Quarts value to US Pints
	def to_uspints(value), do: value / 0.41633692023319535616
	# Converts the supplied Quarts value to US Gallons
	def to_usgallons(value), do: value / 3.3306953618655629312
	# Converts the supplied Quarts value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 0.026021057514574708736
	# Converts the supplied Quarts value to US Cups
	def to_uscups(value), do: value / 0.20816846011659767808
	# Converts the supplied Quarts value to Cubic Metres
	def to_cubicmetres(value), do: value / 879.877
	# Converts the supplied Quarts value to Cubic Feet
	def to_cubicfeet(value), do: value / 24.9153
	# Converts the supplied Quarts value to Cubic Inches
	def to_cubicinches(value), do: value * 69.3549
	# Converts the supplied Quarts value to Oil Barrels
	def to_oilbarrels(value), do: value / 139.889
end

# Tablespoons conversion functions
defmodule PutridParrot.Units.Tablespoons do
	# Converts the supplied Tablespoons value to Millilitres
	def to_millilitres(value), do: value * 17.758171402343747584
	# Converts the supplied Tablespoons value to Litres
	def to_litres(value), do: value * 0.017758171402343747584
	# Converts the supplied Tablespoons value to Kilolitres
	def to_kilolitres(value), do: value * 0.000017758171402343747
	# Converts the supplied Tablespoons value to Teaspoons
	def to_teaspoons(value), do: value * 3.0
	# Converts the supplied Tablespoons value to Quarts
	def to_quarts(value), do: value / 64.0
	# Converts the supplied Tablespoons value to Pints
	def to_pints(value), do: value / 32.0
	# Converts the supplied Tablespoons value to Gallons
	def to_gallons(value), do: value / 256.0
	# Converts the supplied Tablespoons value to Fluid Ounces
	def to_fluidounces(value), do: value / 1.6
	# Converts the supplied Tablespoons value to US Teaspoons
	def to_usteaspoons(value), do: value / 0.27755794682213023744
	# Converts the supplied Tablespoons value to US Tablespoons
	def to_ustablespoons(value), do: value / 0.83267384046639071232
	# Converts the supplied Tablespoons value to US Quarts
	def to_usquarts(value), do: value / 53.291125789849001984
	# Converts the supplied Tablespoons value to US Pints
	def to_uspints(value), do: value / 26.645562894924500992
	# Converts the supplied Tablespoons value to US Gallons
	def to_usgallons(value), do: value / 213.16450315939602432
	# Converts the supplied Tablespoons value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 1.6653476809327814656
	# Converts the supplied Tablespoons value to US Cups
	def to_uscups(value), do: value / 13.322781447462250496
	# Converts the supplied Tablespoons value to Cubic Metres
	def to_cubicmetres(value), do: value / 56312.1
	# Converts the supplied Tablespoons value to Cubic Feet
	def to_cubicfeet(value), do: value / 1594.58
	# Converts the supplied Tablespoons value to Cubic Inches
	def to_cubicinches(value), do: value * 1.08367
	# Converts the supplied Tablespoons value to Oil Barrels
	def to_oilbarrels(value), do: value / 8952.91
end

# Teaspoons conversion functions
defmodule PutridParrot.Units.Teaspoons do
	# Converts the supplied Teaspoons value to Millilitres
	def to_millilitres(value), do: value * 5.9193904674479161344
	# Converts the supplied Teaspoons value to Litres
	def to_litres(value), do: value * 0.005919390467447916134
	# Converts the supplied Teaspoons value to Kilolitres
	def to_kilolitres(value), do: value * 0.000005919390467447916
	# Converts the supplied Teaspoons value to Tablespoons
	def to_tablespoons(value), do: value / 3.0
	# Converts the supplied Teaspoons value to Quarts
	def to_quarts(value), do: value / 192.0
	# Converts the supplied Teaspoons value to Pints
	def to_pints(value), do: value / 96.0
	# Converts the supplied Teaspoons value to Gallons
	def to_gallons(value), do: value / 768.0
	# Converts the supplied Teaspoons value to Fluid Ounces
	def to_fluidounces(value), do: value / 4.8
	# Converts the supplied Teaspoons value to US Teaspoons
	def to_usteaspoons(value), do: value / 0.83267384046639071232
	# Converts the supplied Teaspoons value to US Tablespoons
	def to_ustablespoons(value), do: value / 2.4980215213991718912
	# Converts the supplied Teaspoons value to US Quarts
	def to_usquarts(value), do: value / 159.87337736954701824
	# Converts the supplied Teaspoons value to US Pints
	def to_uspints(value), do: value / 79.936688684773507072
	# Converts the supplied Teaspoons value to US Gallons
	def to_usgallons(value), do: value / 639.49350947818807296
	# Converts the supplied Teaspoons value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 4.9960430427983437824
	# Converts the supplied Teaspoons value to US Cups
	def to_uscups(value), do: value / 39.968344342386753536
	# Converts the supplied Teaspoons value to Cubic Metres
	def to_cubicmetres(value), do: value / 168936.0
	# Converts the supplied Teaspoons value to Cubic Feet
	def to_cubicfeet(value), do: value / 4783.74
	# Converts the supplied Teaspoons value to Cubic Inches
	def to_cubicinches(value), do: value / 2.76837
	# Converts the supplied Teaspoons value to Oil Barrels
	def to_oilbarrels(value), do: value / 26858.7
end

# US Cups conversion functions
defmodule PutridParrot.Units.USCups do
	# Converts the supplied US Cups value to Millilitres
	def to_millilitres(value), do: value * 236.58823649999998976
	# Converts the supplied US Cups value to Litres
	def to_litres(value), do: value * 0.23658823649999998976
	# Converts the supplied US Cups value to Kilolitres
	def to_kilolitres(value), do: value * 0.000236588236499999989
	# Converts the supplied US Cups value to Teaspoons
	def to_teaspoons(value), do: value * 39.968344342386753536
	# Converts the supplied US Cups value to Tablespoons
	def to_tablespoons(value), do: value * 13.322781447462250496
	# Converts the supplied US Cups value to Quarts
	def to_quarts(value), do: value * 0.20816846011659767808
	# Converts the supplied US Cups value to Pints
	def to_pints(value), do: value * 0.41633692023319535616
	# Converts the supplied US Cups value to Gallons
	def to_gallons(value), do: value * 0.052042115029149417472
	# Converts the supplied US Cups value to Fluid Ounces
	def to_fluidounces(value), do: value * 8.3267384046639071232
	# Converts the supplied US Cups value to US Teaspoons
	def to_usteaspoons(value), do: value * 48.0
	# Converts the supplied US Cups value to US Tablespoons
	def to_ustablespoons(value), do: value * 16.0
	# Converts the supplied US Cups value to US Quarts
	def to_usquarts(value), do: value / 4.0
	# Converts the supplied US Cups value to US Pints
	def to_uspints(value), do: value / 2.0
	# Converts the supplied US Cups value to US Gallons
	def to_usgallons(value), do: value / 16.0
	# Converts the supplied US Cups value to US Fluid Ounces
	def to_usfluidounces(value), do: value * 8.0
	# Converts the supplied US Cups value to Cubic Metres
	def to_cubicmetres(value), do: value / 4166.67
	# Converts the supplied US Cups value to Cubic Feet
	def to_cubicfeet(value), do: value / 117.987
	# Converts the supplied US Cups value to Cubic Inches
	def to_cubicinches(value), do: value * 14.6457
	# Converts the supplied US Cups value to Oil Barrels
	def to_oilbarrels(value), do: value / 662.447
end

# US Fluid Ounces conversion functions
defmodule PutridParrot.Units.USFluidOunces do
	# Converts the supplied US Fluid Ounces value to Millilitres
	def to_millilitres(value), do: value * 29.573529562499997696
	# Converts the supplied US Fluid Ounces value to Litres
	def to_litres(value), do: value * 0.029573529562499997696
	# Converts the supplied US Fluid Ounces value to Kilolitres
	def to_kilolitres(value), do: value * 0.0000295735296
	# Converts the supplied US Fluid Ounces value to Teaspoons
	def to_teaspoons(value), do: value * 4.9960430427983437824
	# Converts the supplied US Fluid Ounces value to Tablespoons
	def to_tablespoons(value), do: value * 1.6653476809327814656
	# Converts the supplied US Fluid Ounces value to Quarts
	def to_quarts(value), do: value * 0.026021057514574708736
	# Converts the supplied US Fluid Ounces value to Pints
	def to_pints(value), do: value * 0.052042115029149417472
	# Converts the supplied US Fluid Ounces value to Gallons
	def to_gallons(value), do: value * 0.006505264378643677184
	# Converts the supplied US Fluid Ounces value to Fluid Ounces
	def to_fluidounces(value), do: value * 1.0408423005829883904
	# Converts the supplied US Fluid Ounces value to US Teaspoons
	def to_usteaspoons(value), do: value * 6.0
	# Converts the supplied US Fluid Ounces value to US Tablespoons
	def to_ustablespoons(value), do: value * 2.0
	# Converts the supplied US Fluid Ounces value to US Quarts
	def to_usquarts(value), do: value / 32.0
	# Converts the supplied US Fluid Ounces value to US Pints
	def to_uspints(value), do: value / 16.0
	# Converts the supplied US Fluid Ounces value to US Gallons
	def to_usgallons(value), do: value / 128.0
	# Converts the supplied US Fluid Ounces value to US Cups
	def to_uscups(value), do: value / 8.0
	# Converts the supplied US Fluid Ounces value to Cubic Metres
	def to_cubicmetres(value), do: value / 33814.0
	# Converts the supplied US Fluid Ounces value to Cubic Feet
	def to_cubicfeet(value), do: value / 957.506
	# Converts the supplied US Fluid Ounces value to Cubic Inches
	def to_cubicinches(value), do: value * 1.80469
	# Converts the supplied US Fluid Ounces value to Oil Barrels
	def to_oilbarrels(value), do: value / 5376.0
end

# US Gallons conversion functions
defmodule PutridParrot.Units.USGallons do
	# Converts the supplied US Gallons value to Millilitres
	def to_millilitres(value), do: value * 3785.411784
	# Converts the supplied US Gallons value to Litres
	def to_litres(value), do: value * 3.785411784
	# Converts the supplied US Gallons value to Kilolitres
	def to_kilolitres(value), do: value * 0.003785411784
	# Converts the supplied US Gallons value to Teaspoons
	def to_teaspoons(value), do: value * 639.49350947818807296
	# Converts the supplied US Gallons value to Tablespoons
	def to_tablespoons(value), do: value * 213.16450315939602432
	# Converts the supplied US Gallons value to Quarts
	def to_quarts(value), do: value * 3.3306953618655629312
	# Converts the supplied US Gallons value to Pints
	def to_pints(value), do: value * 6.6613907237311258624
	# Converts the supplied US Gallons value to Gallons
	def to_gallons(value), do: value * 0.83267384046639071232
	# Converts the supplied US Gallons value to Fluid Ounces
	def to_fluidounces(value), do: value * 133.22781447462252544
	# Converts the supplied US Gallons value to US Teaspoons
	def to_usteaspoons(value), do: value * 768.0
	# Converts the supplied US Gallons value to US Tablespoons
	def to_ustablespoons(value), do: value * 256.0
	# Converts the supplied US Gallons value to US Quarts
	def to_usquarts(value), do: value * 4.0
	# Converts the supplied US Gallons value to US Pints
	def to_uspints(value), do: value * 8.0
	# Converts the supplied US Gallons value to US Fluid Ounces
	def to_usfluidounces(value), do: value * 128.0
	# Converts the supplied US Gallons value to US Cups
	def to_uscups(value), do: value * 16.0
	# Converts the supplied US Gallons value to Cubic Metres
	def to_cubicmetres(value), do: value / 264.172
	# Converts the supplied US Gallons value to Cubic Feet
	def to_cubicfeet(value), do: value / 7.48052
	# Converts the supplied US Gallons value to Cubic Inches
	def to_cubicinches(value), do: value * 231.0
	# Converts the supplied US Gallons value to Oil Barrels
	def to_oilbarrels(value), do: value / 42.0
end

# US Pints conversion functions
defmodule PutridParrot.Units.USPints do
	# Converts the supplied US Pints value to Millilitres
	def to_millilitres(value), do: value * 473.17647299999997952
	# Converts the supplied US Pints value to Litres
	def to_litres(value), do: value * 0.47317647299999997952
	# Converts the supplied US Pints value to Kilolitres
	def to_kilolitres(value), do: value * 0.000473176472999999979
	# Converts the supplied US Pints value to Teaspoons
	def to_teaspoons(value), do: value * 79.936688684773507072
	# Converts the supplied US Pints value to Tablespoons
	def to_tablespoons(value), do: value * 26.645562894924500992
	# Converts the supplied US Pints value to Quarts
	def to_quarts(value), do: value * 0.41633692023319535616
	# Converts the supplied US Pints value to Pints
	def to_pints(value), do: value * 0.83267384046639071232
	# Converts the supplied US Pints value to Gallons
	def to_gallons(value), do: value * 0.10408423005829883904
	# Converts the supplied US Pints value to Fluid Ounces
	def to_fluidounces(value), do: value * 16.653476809327814656
	# Converts the supplied US Pints value to US Teaspoons
	def to_usteaspoons(value), do: value * 96.0
	# Converts the supplied US Pints value to US Tablespoons
	def to_ustablespoons(value), do: value * 32.0
	# Converts the supplied US Pints value to US Quarts
	def to_usquarts(value), do: value / 2.0
	# Converts the supplied US Pints value to US Gallons
	def to_usgallons(value), do: value / 8.0
	# Converts the supplied US Pints value to US Fluid Ounces
	def to_usfluidounces(value), do: value * 16.0
	# Converts the supplied US Pints value to US Cups
	def to_uscups(value), do: value * 2.0
	# Converts the supplied US Pints value to Cubic Metres
	def to_cubicmetres(value), do: value / 2113.38
	# Converts the supplied US Pints value to Cubic Feet
	def to_cubicfeet(value), do: value / 59.8442
	# Converts the supplied US Pints value to Cubic Inches
	def to_cubicinches(value), do: value * 28.875
	# Converts the supplied US Pints value to Oil Barrels
	def to_oilbarrels(value), do: value / 336.0
end

# US Quarts conversion functions
defmodule PutridParrot.Units.USQuarts do
	# Converts the supplied US Quarts value to Millilitres
	def to_millilitres(value), do: value * 946.35294599999995904
	# Converts the supplied US Quarts value to Litres
	def to_litres(value), do: value * 0.94635294599999995904
	# Converts the supplied US Quarts value to Kilolitres
	def to_kilolitres(value), do: value * 0.000946352945999999959
	# Converts the supplied US Quarts value to Teaspoons
	def to_teaspoons(value), do: value * 159.87337736954701824
	# Converts the supplied US Quarts value to Tablespoons
	def to_tablespoons(value), do: value * 53.291125789849001984
	# Converts the supplied US Quarts value to Quarts
	def to_quarts(value), do: value * 0.83267384046639071232
	# Converts the supplied US Quarts value to Pints
	def to_pints(value), do: value * 1.6653476809327814656
	# Converts the supplied US Quarts value to Gallons
	def to_gallons(value), do: value * 0.20816846011659767808
	# Converts the supplied US Quarts value to Fluid Ounces
	def to_fluidounces(value), do: value * 33.306953618655629312
	# Converts the supplied US Quarts value to US Teaspoons
	def to_usteaspoons(value), do: value * 192.0
	# Converts the supplied US Quarts value to US Tablespoons
	def to_ustablespoons(value), do: value * 64.0
	# Converts the supplied US Quarts value to US Pints
	def to_uspints(value), do: value * 2.0
	# Converts the supplied US Quarts value to US Gallons
	def to_usgallons(value), do: value / 4.0
	# Converts the supplied US Quarts value to US Fluid Ounces
	def to_usfluidounces(value), do: value * 32.0
	# Converts the supplied US Quarts value to US Cups
	def to_uscups(value), do: value * 4.0
	# Converts the supplied US Quarts value to Cubic Metres
	def to_cubicmetres(value), do: value / 1056.69
	# Converts the supplied US Quarts value to Cubic Feet
	def to_cubicfeet(value), do: value / 29.9221
	# Converts the supplied US Quarts value to Cubic Inches
	def to_cubicinches(value), do: value * 57.75
	# Converts the supplied US Quarts value to Oil Barrels
	def to_oilbarrels(value), do: value / 168.0
end

# US Tablespoons conversion functions
defmodule PutridParrot.Units.USTablespoons do
	# Converts the supplied US Tablespoons value to Millilitres
	def to_millilitres(value), do: value * 14.786764781249998848
	# Converts the supplied US Tablespoons value to Litres
	def to_litres(value), do: value * 0.014786764781249998848
	# Converts the supplied US Tablespoons value to Kilolitres
	def to_kilolitres(value), do: value * 0.000014786764781249998
	# Converts the supplied US Tablespoons value to Teaspoons
	def to_teaspoons(value), do: value * 2.4980215213991718912
	# Converts the supplied US Tablespoons value to Tablespoons
	def to_tablespoons(value), do: value * 0.83267384046639071232
	# Converts the supplied US Tablespoons value to Quarts
	def to_quarts(value), do: value * 0.013010528757287354368
	# Converts the supplied US Tablespoons value to Pints
	def to_pints(value), do: value * 0.026021057514574708736
	# Converts the supplied US Tablespoons value to Gallons
	def to_gallons(value), do: value * 0.003252632189321838592
	# Converts the supplied US Tablespoons value to Fluid Ounces
	def to_fluidounces(value), do: value * 0.52042115029149417472
	# Converts the supplied US Tablespoons value to US Teaspoons
	def to_usteaspoons(value), do: value * 3.0
	# Converts the supplied US Tablespoons value to US Quarts
	def to_usquarts(value), do: value / 64.0
	# Converts the supplied US Tablespoons value to US Pints
	def to_uspints(value), do: value / 32.0
	# Converts the supplied US Tablespoons value to US Gallons
	def to_usgallons(value), do: value / 256.0
	# Converts the supplied US Tablespoons value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 2.0
	# Converts the supplied US Tablespoons value to US Cups
	def to_uscups(value), do: value / 16.0
	# Converts the supplied US Tablespoons value to Cubic Metres
	def to_cubicmetres(value), do: value / 67628.0
	# Converts the supplied US Tablespoons value to Cubic Feet
	def to_cubicfeet(value), do: value / 1915.01
	# Converts the supplied US Tablespoons value to Cubic Inches
	def to_cubicinches(value), do: value / 1.10823
	# Converts the supplied US Tablespoons value to Oil Barrels
	def to_oilbarrels(value), do: value / 10752.0
end

# US Teaspoons conversion functions
defmodule PutridParrot.Units.USTeaspoons do
	# Converts the supplied US Teaspoons value to Millilitres
	def to_millilitres(value), do: value * 4.928921593749999616
	# Converts the supplied US Teaspoons value to Litres
	def to_litres(value), do: value * 0.004928921593749999616
	# Converts the supplied US Teaspoons value to Kilolitres
	def to_kilolitres(value), do: value * 0.000004928921593749999
	# Converts the supplied US Teaspoons value to Teaspoons
	def to_teaspoons(value), do: value * 0.83267384046639071232
	# Converts the supplied US Teaspoons value to Tablespoons
	def to_tablespoons(value), do: value * 0.27755794682213023744
	# Converts the supplied US Teaspoons value to Quarts
	def to_quarts(value), do: value * 0.004336842919095784243
	# Converts the supplied US Teaspoons value to Pints
	def to_pints(value), do: value * 0.008673685838191568486
	# Converts the supplied US Teaspoons value to Gallons
	def to_gallons(value), do: value * 0.00108421072977394606
	# Converts the supplied US Teaspoons value to Fluid Ounces
	def to_fluidounces(value), do: value * 0.1734737167638313984
	# Converts the supplied US Teaspoons value to US Tablespoons
	def to_ustablespoons(value), do: value / 3.0
	# Converts the supplied US Teaspoons value to US Quarts
	def to_usquarts(value), do: value / 192.0
	# Converts the supplied US Teaspoons value to US Pints
	def to_uspints(value), do: value / 96.0
	# Converts the supplied US Teaspoons value to US Gallons
	def to_usgallons(value), do: value / 768.0
	# Converts the supplied US Teaspoons value to US Fluid Ounces
	def to_usfluidounces(value), do: value / 6.0
	# Converts the supplied US Teaspoons value to US Cups
	def to_uscups(value), do: value / 48.0
	# Converts the supplied US Teaspoons value to Cubic Metres
	def to_cubicmetres(value), do: value / 202884.0
	# Converts the supplied US Teaspoons value to Cubic Feet
	def to_cubicfeet(value), do: value / 5745.04
	# Converts the supplied US Teaspoons value to Cubic Inches
	def to_cubicinches(value), do: value / 3.32468
	# Converts the supplied US Teaspoons value to Oil Barrels
	def to_oilbarrels(value), do: value / 32256.0
end
